# -*- coding: utf-8 -*-
"""ปุ้มปุ้ย 03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oybEpD7v6df_Ewdvpq3uu6IN7DZpV1aj
"""

# ============================================================
# 🔒 LOCKED DEPENDENCIES — เวอร์ชันที่ผ่านการทดสอบ (Python 3.12)
#    ทดสอบล่าสุด: ใช้งานได้ครบทุกตัว
#    ⚠️ ถ้าวันใด pip install ตัวใดตัวหนึ่ง error → Colab อาจเปลี่ยน Python
#       ให้ดู LOCK CHECK ด้านล่างว่าเวอร์ชันไหนเพี้ยน
# ============================================================
# 📦 VS Code: ติดตั้งครั้งเดียวจาก Terminal (อย่ารันในไฟล์นี้):
#     pip install -r requirements.txt
#   หรือ:
#     pip install pandas==2.2.2 xlrd==2.0.1 openpyxl==3.1.5 rapidfuzz==3.10.1 \
#                 matplotlib==3.9.2 plotly==5.24.1 tqdm==4.67.1 pythainlp==5.0.5
# (บรรทัด !pip ของ Colab ถูกตัดออก เพราะใช้กับไฟล์ .py ปกติไม่ได้)
# ============================================================


# ============================================================
# 🧾 Invoice & Tax Document Audit System v5.8
# 41 Rules + Thai Typo + 2-Tier Verification + 5 Numerical Specs + Analytics
# ============================================================
# v5.8 fixes (จาก v5.7):
#  [FIX-1] TAX001  : wider tax_id scan (no keyword required) + Excel numeric cells
#  [FIX-2] ADDR001 : ซอย fuzzy match + normalize '/' + รองรับ ซ.
#  [FIX-3] BR001/2 : สแกนรหัสสาขา/สนญ. ทั้ง block ไม่จำกัดแค่ company name line
#  [FIX-4] NBSP    : อธิบาย NBSP/ZWS/BOM ใน detail message
#  [FIX-5] PyThaiNLP: partial whitelist (stem in CONSTRUCTION_DICT → skip)
#                     + similarity guard 75→80
#  [FIX-6] IV gap  : split severity (≥3 consecutive=CRITICAL, ไม่งั้น=WARNING)
#  [FIX-7] ITM001  : ตรวจ plausible discount → skip flag (1-50% ส่วนลด=legit)
#  [FIX-8] DT001   : รองรับ filename month range "69.03-04"
#  [FIX-9] ITM007  : ชื่อสั้น+อยู่ใน CONSTRUCTION_DICT/category keywords → skip
# ============================================================
# 🛡️ v6.1 STABILITY HARDENING (ไม่เพิ่มฟีเจอร์ — แก้ความเสถียร/กันพังเท่านั้น;
#    business logic เดิมคงไว้ 100%, ผลตรวจบิลที่อ่านได้เหมือนเดิมทุกประการ):
#  [S1-CRITICAL] main() parsing loop : ห่อ try/except ต่อไฟล์ — 1 ไฟล์เพี้ยน = ข้าม
#                ไฟล์นั้น ไม่ใช่ล้มทั้ง batch (เดิม parse_filename / merge_continuation_bills /
#                check_iv_format / check_filename_consistency อยู่นอก try → เสียงานทั้งหมด)
#  [S2-CRITICAL] parse_file()        : ปิด ExcelFile ใน finally — กัน file-handle/RAM รั่ว
#                ตอนวนอ่านไฟล์จำนวนมาก (เดิมไม่เคยปิด → เสี่ยง OSError: Too many open files)
#  [S3-MEDIUM]   TOR item builder    : เพิ่มคีย์ 'name_raw' ให้ schema เท่า parser หลัก
#  [S3-MEDIUM]   ITM004 (r_itm004)   : อ่าน name_raw แบบ .get() — เดิม KeyError บนบิล TOR
#                ทำให้กฎตรวจคำสะกด/อักขระแปลกถูกข้ามเงียบทุกบิล TOR (สูญเสียการตรวจ)
#  [S5-LOW]      main()              : เคลียร์ _PYTHAINLP_CACHE ตอนเริ่มรอบด้วย กันโตข้ามรอบ
# ============================================================
# 🎨 v6.3 REPORT POLISH (เฉพาะรายงานคลีน — ไม่แตะ business logic/ผลตรวจ):
#  - แถบหัวเรื่องสไตล์ผู้บริหาร (ดำ+เส้นแดง+ซับไตเติล) ทุกชีตข้อมูล
#  - เส้น accent แดงใต้หัวตาราง + แท็บชีตสีตามประเภท (หาง่าย ดูมือโปร)
#  - ตรึงคอลัมน์ระบุไฟล์ (บริษัท/ไฟล์/IV) ในชีต 'รายการสินค้า'/'ทุกบิล'
#    → เลื่อนตารางไปขวาแล้วยังเห็นว่าบรรทัดนั้นมาจากไฟล์ไหน
#  หมายเหตุ: คอลัมน์ 'ไฟล์' มีอยู่แล้วในชีตรายการสินค้า/ทุกบิล/Error Report
#  (รายงานคลีนไม่ถูกอ่านกลับโดย analytics → ปรับหน้าตาได้ปลอดภัย)
# ============================================================
# 🎨 v6.4 MINIMAL RESTYLE (เฉพาะหน้าตารายงานคลีน — โครงสร้าง/คอลัมน์/ข้อมูล/ผลตรวจ
#    เหมือนเดิม 100%, เปลี่ยนเฉพาะ "สไตล์" ให้เรียบหรู สมผู้บริหาร):
#  - palette ใหม่: ดำสนิท→ถ่านสเลตสุภาพ (#1F2A37), แดงสด Tesla (#E82127)→
#    ใช้สีเฉพาะระดับความรุนแรงแบบหม่น (อิฐ/ส้มเอิร์ธ/เขียว/น้ำเงิน)
#  - เส้น accent: แดงหนา (medium/3-4px) → ทองหม่นบางๆ (#B08D57 thin/2px) จุดเดียว
#  - ตัวอักษรเนื้อหานุ่มขึ้น (#3F4A5A) + ซับไตเติลเทาคูล — อ่านสบายตา
#  - คงทุกอย่าง: 7 ชีต, ตรึงคอลัมน์, ฟิลเตอร์, แถวสรุป, สีแท็บ, รูปแบบตัวเลข
# รันใน VS Code ได้เลย:  python audit_v58_vscode.py

# ============================================================
# 🔧 v9 INTEGRITY + ACCURACY (รวมแพตช์ — ตรวจสอบกับไฟล์จริง 75 ไฟล์/580 บิล:
#     regression=0 ยอดเงินทุกบิลเท่าเดิม | system issues=0 | bills เท่าเดิม)
#  [P0][FIX-1] _pb_finalize_amounts(): ติด provenance ('ocr'|'derived'|'item_sum')
#              ให้ยอด subtotal/vat/total — ไม่เปลี่ยนพฤติกรรมการเติมยอดเดิม
#              + กฎใหม่ VAT010: ยอดที่ "ระบบคำนวณเอง" จะไม่ถูกถือว่าผ่าน VAT001/002/003
#              เงียบ ๆ (false-clean) แต่ตีกลับให้คนตรวจยอด VAT บนเอกสาร (58% ของบิล)
#  [P2][FIX-2] _kw_in_name(): กัน substring คำสั้นกำกวมใน ITM005 ('สี' ใน 'สี่'/'ทาสี')
#  [P2][FIX-3] CONSTRUCTION_DICT += 'แผ่นตัด' (คนละสินค้ากับ 'แผ่นขัด') แก้ ITM011 FP
#  [P2][FIX-4] ITM010: เลิกข้อความ 'ผิด -> ถูก -> ผิด' ที่ซ้ำซ้อน (การตรวจเดิมถูกต้อง)
# ============================================================


import pandas as pd
import state
import re, os, glob, json, unicodedata, traceback, statistics, gc
import sqlite3, time, urllib.parse, urllib.request
import file_guard   # [OBJ-OFFLINE] guard ไฟล์อินพุต untrusted (zip-bomb/resource) ก่อน parse
from datetime import datetime, timedelta, timezone
from collections import defaultdict, Counter
try:
    import xlrd                       # v8.2: ใช้เฉพาะอ่านไฟล์ .xls (เก่า) — ไม่มีก็รัน .xlsx ได้ปกติ ไม่ crash ตอน import
except ImportError:
    xlrd = None
try:
    from rapidfuzz import fuzz        # v8.2: หัวใจ fuzzy matching — ถ้าไม่มีให้แจ้งชัดเจน (แทน ModuleNotFoundError ปริศนา)
except ImportError:
    raise SystemExit('❌ ต้องติดตั้ง rapidfuzz ก่อนรัน:  pip install rapidfuzz')
try:
    from tqdm import tqdm
except ImportError:                   # v8.2: ไม่มีก็รันได้ (แค่ไม่มีแถบ progress)
    def tqdm(iterable=None, *args, **kwargs):
        return iterable if iterable is not None else iter(())
try:
    import matplotlib
    matplotlib.use('Agg')          # VS Code: ไม่มีหน้าต่าง GUI ของ Jupyter → ใช้ backend แบบเซฟไฟล์
    import matplotlib.pyplot as plt
except ImportError:
    # v9.1 [FINDING-1]: matplotlib เป็นชั้นแสดงผล (version_gate จัดเป็น "degrade ได้/WARN")
    #   แต่เดิม import แบบแข็ง → ขาดแล้ว crash ตอน import ขัดกับสิ่งที่ gate บอก.
    #   ทำให้ optional แบบเดียวกับ reporting.py (plt=None) → audit รันได้ ไม่มี dashboard เท่านั้น.
    plt = None

# ============================================================
# 🖥️ VS Code COMPAT SHIM — แทน IPython.display ของ Colab/Jupyter
#   ใน Colab: display(HTML(...)) จะแสดงผลในเซลล์
#   ใน VS Code (.py ธรรมดา): ไม่มีตัวแสดงผล → เก็บ HTML ทั้งหมดไว้
#   แล้วเขียนเป็นไฟล์ audit_dashboard_report.html ตอนจบโปรแกรม (เปิดด้วยเบราว์เซอร์)
# ============================================================
try:
    from IPython.display import display, HTML          # ถ้าเผลอรันใน Jupyter ก็ยังใช้ได้
    _IN_NOTEBOOK = True
except Exception:
    _IN_NOTEBOOK = False
    _CAPTURED_HTML = []

    class HTML:                                          # ตัวแทน HTML object
        def __init__(self, data=''):
            self.data = data

    def display(obj=None, *args, **kwargs):              # ตัวแทน display()
        if obj is None:
            return
        data = getattr(obj, 'data', None)
        if data is not None:
            _CAPTURED_HTML.append(str(data))             # เก็บไว้เขียนไฟล์ทีหลัง
        else:
            print(obj)

    import atexit
    def _dump_html_report():
        if not _CAPTURED_HTML:
            return
        out = 'audit_dashboard_report.html'
        try:
            with open(out, 'w', encoding='utf-8') as f:
                f.write('<!DOCTYPE html><html lang="th"><head><meta charset="utf-8">'
                        '<meta name="viewport" content="width=device-width,initial-scale=1">'
                        '<title>Audit Dashboard v5.8</title>'
                        '<style>body{font-family:"Noto Sans Thai",-apple-system,Segoe UI,'
                        'Tahoma,sans-serif;background:#F8FAFC;margin:0;padding:24px;}</style>'
                        '</head><body>')
                f.write('\n'.join(_CAPTURED_HTML))
                f.write('</body></html>')
            print(f'\n🖥️  Dashboard (HTML) บันทึกแล้ว → {os.path.abspath(out)}')
            print('    เปิดไฟล์นี้ด้วยเบราว์เซอร์เพื่อดู Executive Dashboard')
        except Exception as e:
            print(f'⚠️ เขียน dashboard HTML ไม่ได้: {e}')
    atexit.register(_dump_html_report)

from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter
import warnings
from decimal import Decimal, ROUND_HALF_UP
warnings.filterwarnings('ignore')
if plt is not None:                       # v9.1 [FINDING-1]: guard เมื่อ matplotlib ขาด (plt=None)
    plt.rcParams['font.family'] = 'DejaVu Sans'

# [P-DAG พาส2b] PyThaiNLP import guard → thai_text.py (main ได้ PYTHAINLP_AVAILABLE จาก re-export)


# --- slice 1: static config & constants extracted to config.py ---
from config import *
from puopuy_core import (to_conf01, normalize_text, has_hidden_chars, clean_tax_id,
                         _taxid_checksum_ok, remove_branch_suffix, _raw_company_form,
                         extract_branch, safe)   # [P-DAG เฟส1] leaf utils ที่แยกออก (verbatim, ผลเดิม 100%)
from puopuy_dates import parse_date_any, _ivp_year2_to_ce, _ivp_year4_to_ce   # [P-DAG เฟส2]
from puopuy_units import extract_unit_hint, _unit_canon, _D, _vat_tolerance   # [P-DAG เฟส2]
from rules_engine import *   # [P-DAG พาส1] 56 กฎ + RULES + run_rules (re-export ให้ validators/reporting/agents)
import rules_engine as _rules_engine   # อ้างอิงตรงสำหรับ debug/ตรวจสอบ
from diagnostics import *   # [P-DAG พาส2a] system logger (re-export ให้ validators/reporting)
import diagnostics as _diagnostics
from thai_text import *   # [P-DAG พาส2b] thai NLP (re-export: PYTHAINLP_AVAILABLE ให้ reporting, fns ให้ rules)
from parser import *   # [P-DAG พาส2c] data-extraction layer (re-export ให้ main/agents)
import parser as _parser
import thai_text as _thai_text
from core_utils import *   # [P-DAG พาส3b] shared helpers (sort_bills_by_date/parse_address_input/clean_pp20_address)
import core_utils as _core_utils
from webverify import *   # [P-DAG พาส3c] online product-verification (web governor/cache/tiers) — re-export
import webverify as _webverify
from master import *   # [P-DAG พาส3d] master-data layer (input/load/save/parse master) — re-export
import master as _master
# alias ระดับ main → cache "ตัวเดียวกัน" ใน state (reset ใช้ .clear() คง identity)
_FUZZY_DICT_CACHE = state._FUZZY_DICT_CACHE
_PYTHAINLP_CACHE = state._PYTHAINLP_CACHE
# alias ระดับ main → ชี้ "list ตัวเดียวกัน" ใน state (reporting import by-reference จากตรงนี้)
#   reset ใช้ .clear() (ไม่ rebind) → main alias + reporting ref + diagnostics เห็น object เดียวกันเสมอ
_SYSTEM_ISSUES = state._SYSTEM_ISSUES
_SYSTEM_ISSUE_SEEN = state._SYSTEM_ISSUE_SEEN



# ============================================================
# 🆕 v5.4 SPEC CONFIGURATIONS
# ============================================================



# [P-DAG เฟส1] to_conf01 ย้ายไป puopuy_core.py










# [P-DAG พาส3c] web/verify layer (governor _WEB_STATE, web_request, sqlite cache, tier1/tier2 verify, run_product_verification)
#   ย้ายไป webverify.py (online product-verification, leaf) — main re-export ผ่าน `from webverify import *` ด้านบน












# === v9 [ACCURACY]: เพิ่มคำสินค้าจริงที่ขาด → กัน ITM011 ฟ้อง "แผ่นตัด" ว่าใกล้ "แผ่นขัด"
#     (แผ่นตัด=ใบตัด/cutting disc, แผ่นขัด=ใบขัด — คนละสินค้า ไม่ใช่คำสะกดผิด)
CONSTRUCTION_DICT.update({'แผ่นตัด'})

# === v5.8q PATCH 3: เพิ่มชื่อสินค้าที่ถูกต้อง แก้ ITM011/ITM012 false positive ===
CONSTRUCTION_DICT.update({
    'เหล็กแผ่นดำ','เหล็กแผ่นขาว','เหล็กดำ','เหล็กกัลวาไนซ์',
    'รางวายดักส์','รางวายเวย์','สังกะสีแผ่นเรียบ','เมทัลชีท',
    'ตู้สวิตช์บอร์ด','ตู้คอนซูมเมอร์','กล่องพักสาย',
})

# === v8.0 UPGRADE: ขยาย CONSTRUCTION_DICT ไฟฟ้า/ประปา/ไม้/งานระบบ ===
CONSTRUCTION_DICT.update({
    # ไฟฟ้า — อุปกรณ์
    'สวิตช์','สวิตช์ทางเดียว','สวิตช์สองทาง','สวิตช์สามทาง',
    'เต้ารับ','เต้ารับคู่','เต้ารับสาม','เต้าเสียบ',
    'เบรกเกอร์','เบรกเกอร์ลูก','เบรกเกอร์หลัก','เบรกเกอร์กันดูด',
    'เซอร์กิตเบรกเกอร์','เอลซีบี','อาร์ซีบี','อาร์ซีดี',
    'คอนแทคเตอร์','โอเวอร์โหลด','รีเลย์','ไทม์เมอร์',
    'ตู้แผงไฟ','ตู้เมนสวิตช์','ตู้เบรกเกอร์','แผงเมน',
    'สายไฟVAF','สายไฟTHW','สายNYY','สายVCT','สาย CVV',
    'ท่อร้อยสาย','ท่อเหล็กร้อยสาย','ท่อพีวีซีร้อยสาย',
    'กล่องพักสาย','กล่องต่อสาย','กล่องเดินสาย',
    'หัวเทียน','คลิปยึดสาย','ลูกถ้วยไฟฟ้า',
    'มิเตอร์ไฟฟ้า','หม้อแปลง','คาปาซิเตอร์',
    # หลอดไฟ/โคม
    'หลอด LED','หลอดLED','โคม LED','โคมLED',
    'หลอดฟลูออเรสเซนต์','หลอดตะเกียบ','หลอดประหยัดไฟ',
    'โคมฝังฝ้า','โคมติดผนัง','โคมถนน','โคมสปอตไลต์',
    'ดาวน์ไลต์','สปอตไลต์','ฟลัดไลต์',
    # ประปา/งานระบบน้ำ
    'ท่อPVC','ท่อ PVC','ท่อพีวีซี','ท่อCPVC','ท่อ CPVC',
    'ท่อPPR','ท่อ PPR','ท่อเหล็กอาบสังกะสี','ท่อGI',
    'ข้อต่อตรง','ข้อต่องอ','ข้อต่อลด','ข้อต่อสามทาง',
    'ข้องอ90','ข้องอ45','สามทาง','สี่ทาง',
    'วาล์วบอล','วาล์วประตูน้ำ','วาล์วเช็ค','วาล์วนิรภัย',
    'ก๊อกน้ำ','ก๊อกน้ำเย็น','ก๊อกน้ำร้อน','ก๊อกผสม',
    'ฝักบัว','ชักโครก','โถส้วม','อ่างล้างมือ',
    'ถังพักน้ำ','ปั๊มน้ำ','มอเตอร์ปั๊มน้ำ',
    # งานไม้/วัสดุตกแต่ง
    'ไม้อัด','ไม้อัดเคลือบ','ไม้แผ่น','ไม้เนื้ออ่อน','ไม้เนื้อแข็ง',
    'ไม้ฝ้า','ฝ้าเพดาน','ฝ้าตะแกรง','ฝ้าซีเมนต์บอร์ด',
    'ยิปซั่ม','แผ่นยิปซั่ม','คอมพาวด์ยิปซั่ม',
    'ซีเมนต์บอร์ด','ไฟเบอร์ซีเมนต์','วูดเซอร์ไฟต์',
    'กระเบื้องหลังคา','กระเบื้องลอนคู่','กระเบื้องแผ่นเรียบ',
    'สังกะสี','แผ่นสังกะสี','เมทัลชีท','กระเบื้องเหล็ก',
    # ฉนวน/กันความร้อนชื้น
    'ฉนวนกันความร้อน','ฉนวนกันเสียง','ฉนวนใยแก้ว',
    'โฟมกันความร้อน','อลูมิเนียมฟอยล์','กันซึม',
    'ซีลเลอร์','กาวซีลเลอร์','ซิลิโคนกันน้ำ',
    # เครื่องมือ/อุปกรณ์ช่าง
    'สว่านไฟฟ้า','เลื่อยวงเดือน','เลื่อยไฟฟ้า',
    'เครื่องเจียร','เครื่องเชื่อม','ตู้เชื่อม','หน้ากากเชื่อม',
    'ไขควงไฟฟ้า','ประแจ','ประแจเลื่อน','ประแจปากตาย',
    'ตลับเมตร','ระดับน้ำ','ดิ่ง','ฉากสามเหลี่ยม',
    # น็อต/สกรู/ยึด
    'สกรูหัวจม','สกรูหัวกลม','สกรูหัวแบน','สกรูไม้','สกรูเหล็ก',
    'น็อตหกเหลี่ยม','น็อตปีกผีเสื้อ','น็อตเกลียว',
    'แหวนรอง','แหวนสปริง','สลักเกลียว','เดือย',
    'ตะปูตอก','ตะปูลวด','ตะปูสกรู',
    'พุกกำแพง','พุกเคมี','พุกนกแก้ว',
    'ยาแนว','กาวยาง','กาวอีพ็อกซี่',
})






# ============================================================
# 🔒 LOCK CHECK — ตรวจว่าเวอร์ชันยังตรงกับที่ล็อกไว้ (P1: FAIL ดังๆ ไม่ใช่เตือนเงียบ)
#   ใช้ version_gate (source of truth = config._LOCKED) — แทน "พิมพ์ ⚠️ แล้วรันต่อ" เดิม
#   นโยบาย: เพี้ยนระดับอันตราย (major/minor ของ lib หัวใจ, หรือไม่ได้ติดตั้ง) → exit ≠ 0
#           เพี้ยนระดับไม่อันตราย (patch / ชั้นแสดงผล) → เตือน แล้วรันต่อ
#   escape hatch: ตั้ง env PUOPUY_ALLOW_VERSION_MISMATCH=1 เพื่อผ่อนผัน (รับความเสี่ยงเอง)
#   หมายเหตุ: enforce() จะ exit เฉพาะ "เคสที่ควรหยุดจริง" → ปลอดภัยแม้ถูก import โดย harness
# ============================================================
import sys

import version_gate as _version_gate

_version_gate.enforce(strict=False, exit_on_fail=True)

# ============================================================
# 🧹 UTILITIES
# ============================================================
# [P-DAG เฟส2] safe() ย้ายไป puopuy_core.py

# ============================================================
# 🩺 v6.2 OBSERVABILITY — structured system-issue logger
#   เป้าหมาย (TARGET 2): แทน "except: pass / print เฉย ๆ" ในชั้น parse
#   ด้วย record ที่ตามรอยได้ โดย **ไม่แตะ** schema ของ bill/รายงานเดิมเลย
#   - เก็บใน list ระดับโมดูล + พิมพ์รูปแบบมาตรฐาน + เขียน sidecar JSONL
#   - dedupe กัน log ซ้ำ (กัน spam ตามสเปก)
#   - ไม่ทำให้ pipeline ล้ม: ตัว logger เองห่อกันพังไว้
# ============================================================
# [P-DAG พาส2a] _SYSTEM_ISSUES/_SYSTEM_ISSUE_SEEN → state.py ;
#   system_issues_reset/log_system_issue/flush_system_issues_to_disk/_trim_cache → diagnostics.py
#   (main re-export ผ่าน `from diagnostics import *` ด้านบน — อ้าง state._SYSTEM_ISSUES)

# [P-DAG เฟส1] normalize_text/clean_tax_id/... ย้ายไป puopuy_core.py (import ไว้บนสุดแล้ว)
# [P-DAG เฟส2] parse_date_any() ย้ายไป puopuy_dates.py

# ============================================================
# 🆕 [FIX-MERGE] รวมบิลหน้าต่อ — IV ตรง + ลำดับสินค้าต่อเนื่อง
#   เคสจริง: TKH ชีต '3' + '3 (2)' = บิล CB69040116 ใบเดียว (รายการยาวข้ามหน้า)
#   กันพลาด: ชีต '11' + '11(2)' IV คนละเลข = คนละบิล → ไม่รวม
# ============================================================
# [P-DAG พาส3a] parse_filename / merge_continuation_bills / _declared_period_from_filename
#   ย้ายไป parser.py (data-extraction layer) — main re-export ผ่าน `from parser import *` ด้านบน
#   ทำให้ parser พึ่งตัวเองได้ (ลบ _from_main lazy-proxy) + ตัด validators->main cycle


# [P-DAG เฟส2] extract_unit_hint() ย้ายไป puopuy_units.py

# [P-DAG พาส2b] thai_text group → thai_text.py ;
#   _FUZZY_DICT_CACHE/_PYTHAINLP_CACHE → state.py ; PyThaiNLP guard → thai_text.py
#   (main re-export ผ่าน `from thai_text import *` ด้านบน — rules_engine เลิก lazy proxy)



# ============================================================
# [P-DAG พาส2c] ── EXCEL PARSER (read_workbook..parse_file, _dic_*, _pb_*, _tor_*,
#   check_iv_format, taxid/branch scan, amounts, address, audit Text→num) → parser.py
#   (main re-export ผ่าน `from parser import *` ด้านบน)


# [P-DAG พาส3b] clean_pp20_address / parse_address_input ย้ายไป core_utils.py (shared helpers)
#   main re-export ผ่าน `from core_utils import *` ด้านบน


# [P-DAG พาส3d] master-data layer (validate_master_entry/save_master/load_master/
#   parse_master_blob/input_master_data) ย้ายไป master.py — main re-export ผ่าน `from master import *`


# [P-DAG พาส1] match_company → ย้ายไป rules_engine.py


# [P-DAG พาส1] load_product_master + PRODUCT_MASTER → ย้ายไป rules_engine.py

# ============================================================
# 🛡️ RULES ENGINE
# ============================================================
# [P-DAG พาส1] add_issue + 56 กฎ + RULES registry + run_rules → ย้ายไป rules_engine.py
#   (main re-export ผ่าน `from rules_engine import *` ด้านบน — RULES/ฟังก์ชันเป็น object เดียวกัน)















# ============================================================
# 🆕 v6.5 — ตัวอ่าน "งวด (ปี/เดือน) ที่ฝังในเลขที่เอกสาร" รองรับหลายฟอร์แมต
#   ใช้กับ DT004 (วันที่ขัดแย้งกับเลข IV) แทนการเดา IV+YYMM แบบตายตัว
#   *ห้ามทำให้การตรวจเดิม (ไทย YYMM) อ่อนลง* — ฟังก์ชันนี้ครอบของเดิม + ขยายเพิ่ม
#
#   หลักการกัน false positive: อ่านงวดจากเลขได้ "แบบมั่นใจ" เท่านั้นจึงเทียบ
#   อ่านไม่ได้/ไม่เข้าโครงปี-เดือน → คืน None = ไม่ฟันธง (เลข running ล้วน/ฟอร์แมตแปลก)
#
#   ฟอร์แมตที่รองรับ (พบจริงในเอกสารไทย):
#     IV6811xxxx / CB-6904-xxxx / IV-68-110141  → พ.ศ. 2 หลัก + เดือน (+วัน/running)
#     J25110023                                  → ค.ศ. 2 หลัก + เดือน + running
#     256811xxxx                                 → พ.ศ. 4 หลัก + เดือน
#     202511xxxx                                 → ค.ศ. 4 หลัก + เดือน
#     INV-2025-001                               → ค.ศ. 4 หลัก (ปีอย่างเดียว ไม่มีเดือน)
#
#   ช่วงปีที่ยอมรับว่าเป็น "ปีจริง" (กันเลข running บังเอิญหน้าตาเหมือนปี) — สองฐานไม่ทับกัน:
#     พ.ศ. 2 หลัก = 58–82 (พ.ศ.2558–2582 ↔ ค.ศ.2015–2039)
#     ค.ศ. 2 หลัก = 15–39 (ค.ศ.2015–2039)
#     พ.ศ. 4 หลัก = 2558–2582 | ค.ศ. 4 หลัก = 2015–2039
# ============================================================
# [P-DAG เฟส2] _ivp_year2_to_ce() ย้ายไป puopuy_dates.py

# [P-DAG เฟส2] _ivp_year4_to_ce() ย้ายไป puopuy_dates.py

# --- validators layer (validators.py) ---
#   [P-DAG พาส3a] validators นำเข้า dependency จาก leaf modules ตรง ๆ แล้ว
#   จึงไม่ต้องมี import-gate / ลำดับนิยามใน main อีก (ตัด validators -> main cycle)
from validators import *



# [P-DAG พาส3f] check_filename_consistency ย้ายไป validators.py — re-export ผ่าน `from validators import *`




# ============================================================
# 🔬 PRODUCT VERIFICATION (Tier 1 + Tier 2)
# ============================================================



# ============================================================
# 📤 UPLOAD
# ============================================================
# [P-DAG พาส3g] get_files_via_upload/drive ย้ายไป parser.py (ชั้นค้นไฟล์) — re-export ผ่าน `from parser import *`















# [P-DAG พาส3b] sort_bills_by_date ย้ายไป core_utils.py (ใช้ร่วม analytics/reporting)

# --- analytics layer (analytics.py) ---
#   [P-DAG พาส3b] analytics นำเข้า dependency จาก leaf modules ตรง ๆ แล้ว (ตัด analytics -> main cycle)
from analytics import *























# ============================================================
# 🆕 v5.8r — เลขที่เอกสาร "ตามหน้าเอกสารจริง" (เก็บขีด/เว้นวรรค)
#   ใช้แสดงในรายงานเท่านั้น — การตรวจสอบยังใช้ iv_number แบบลบขีดเหมือนเดิม
# ============================================================
# [P-DAG พาส2c] _raw_iv_form → parser.py
































# ============================================================
# 📊 v5.5 ANALYTICS MODULE — Pattern Clustering + Plotly Dashboard
# ============================================================

# [P-DAG พาส3e] analytics ตัวคำนวณบริสุทธิ์ (load_audit_excel/cluster_*/detect_*) ย้ายไป analytics.py — re-export ผ่าน `from analytics import *`


















def run_analytics(excel_path=None, sheets=None):
    if not ANALYTICS_CFG['ENABLE']:
        print('⏭️ Analytics Module ปิดอยู่')
        return None
    print('\n' + '='*70)
    print('📊 ANALYTICS MODULE v1.0 — Pattern Clustering + Plotly Dashboard')
    print('='*70)
    if sheets is None:
        if not excel_path:
            print('❌ ต้องระบุ excel_path หรือ sheets')
            return None
        sheets = load_audit_excel(excel_path)
        if not sheets: return None
    items = sheets.get('รายการสินค้า')
    if items is None or len(items) == 0:
        print('⚠️ ไม่พบชีต "รายการสินค้า"')
        return None
    print(f'\n🔬 Clustering ({ANALYTICS_CFG["CLUSTERING_METHOD"]}): {len(items)} items')
    df_clustered = cluster_products(items)
    n_clusters = df_clustered['_cluster_id'].nunique()
    print(f'   พบ {n_clusters} clusters | unique categories: {df_clustered["_category"].nunique()}')
    print('🔍 Anomaly detection...')
    df_clustered = detect_price_outliers(df_clustered)
    df_clustered = detect_unit_anomalies(df_clustered)
    price_out = df_clustered['_price_outlier'].sum() if '_price_outlier' in df_clustered else 0
    unit_out = df_clustered['_unit_rare'].sum() if '_unit_rare' in df_clustered else 0
    print(f'   ราคาผิดปกติ: {price_out} | หน่วยผิดปกติ: {unit_out}')
    print('🎨 สร้าง Plotly figures...')
    figs = build_dashboard_figs(sheets, df_clustered)
    print(f'   สร้าง {len(figs)} charts')
    out_html = ANALYTICS_CFG['DASHBOARD_HTML']
    if '/' not in out_html and excel_path:
        out_html = os.path.join(os.path.dirname(excel_path) or '.', out_html)
    stats = {
        'รายการทั้งหมด': len(items),
        'Clusters': n_clusters,
        'หมวด': df_clustered['_category'].nunique(),
        'ราคาผิดปกติ': int(price_out),
        'หน่วยผิดปกติ': int(unit_out),
    }
    if render_dashboard_html(figs, out_html, stats):
        print(f'\n✅ Dashboard: {out_html}')
        try:
            display(HTML(f'<div style="padding:14px;background:#16A34A;color:white;'
                        f'border-radius:8px;text-align:center;font-weight:600;">'
                        f'📊 Dashboard พร้อมแล้ว: {out_html} ({len(figs)} charts)</div>'))
            print(f'📊 Dashboard บันทึกแล้ว → {os.path.abspath(out_html)}')
        except Exception: pass
        return {'sheets':sheets,'clusters':df_clustered,'figs':figs,'output':out_html}
    return None

# [P-DAG พาส3f] check_duplicate_items ย้ายไป validators.py — re-export ผ่าน `from validators import *`







# [P-DAG พาส3b] thin / bottom_only (openpyxl styles) ย้ายไป config.py — main+reporting รับผ่าน `from config import *`

# --- reporting layer (reporting.py) ---
#   [P-DAG พาส3b] reporting นำเข้า dependency จาก leaf (thai_text/rules_engine/state/core_utils)
#   + style จาก config แล้ว → ตัด reporting -> main cycle, ไม่ต้องมี import-gate ที่นี่
from reporting import *
























def run_self_check(master):
    """v6 SELF-CHECK (ตอนเปิดโปรแกรม): ตรวจ Master JSON ว่าคีย์ครบ/เลขภาษีถูก
    ก่อนเริ่มตรวจบิล — เตือนล่วงหน้า กันผลออกผิดเพราะ master พัง/แก้มือคีย์หาย
    ห่อ try/except ทั้งหมด → พังไม่ได้ ไม่บล็อกการทำงาน
    """
    print('\n' + '─'*70)
    print('🩺 SELF-CHECK: ตรวจความสมบูรณ์ของ Master ก่อนเริ่ม')
    try:
        if not isinstance(master, dict) or not master:
            print('   ⚠️ master ว่าง/ไม่ใช่ dict — ข้ามการตรวจ')
            return
        need = ('name', 'tax_id', 'address_full', 'address_parts')
        miss = {k: [] for k in need}
        bad_tax = []
        for key, m in master.items():
            if not isinstance(m, dict):
                for k in need: miss[k].append(str(key))
                continue
            for k in need:
                if not m.get(k):
                    miss[k].append(str(key))
            tid = clean_tax_id(m.get('tax_id', ''))
            if len(tid) != 13:
                bad_tax.append(f"{key} ({len(tid)} หลัก)")
        n = len(master)
        problems = sum(len(v) for v in miss.values()) + len(bad_tax)
        if problems == 0:
            print(f'   ✅ Master {n} บริษัท — คีย์ครบทุกตัว เลขภาษี 13 หลักทุกราย')
            return
        for k in need:
            if miss[k]:
                ex = ', '.join(miss[k][:3]) + (f' ...(+{len(miss[k])-3})' if len(miss[k]) > 3 else '')
                print(f"   ⚠️ ขาดคีย์ '{k}': {len(miss[k])}/{n} ราย → {ex}")
        if bad_tax:
            ex = ', '.join(bad_tax[:3]) + (f' ...(+{len(bad_tax)-3})' if len(bad_tax) > 3 else '')
            print(f"   ⚠️ เลขภาษีไม่ครบ 13 หลัก: {len(bad_tax)} ราย → {ex}")
        print('   ℹ️ บริษัทที่คีย์หายจะถูกข้ามบางกฎ (โปรแกรมไม่ล้ม) — แนะนำแก้ master ให้ครบ')
    except Exception as e:
        print(f'   ⚠️ self-check ทำงานไม่ครบ ({type(e).__name__}) — ข้ามไป ไม่กระทบการตรวจบิล')






# ============================================================
# 🚦 main() PHASES (extracted, slice 3A) — behavior 100% เดิม
#   ย้ายบล็อกใน main ออกมาเป็นฟังก์ชันชื่อชัด: logic/ลำดับ/print เดิมทุกอย่าง
# ============================================================
def reset_run_state():
    """ล้าง global state ต้นรอบ (กัน state bleed ข้ามรอบใน session ยาว). ไม่แตะ logic."""
    # v5.9 FIX-2(state): ล้าง global state ตอนต้น กันรันซ้ำในเซสชันเดียว (Colab/Jupyter) แล้วค่าค้าง
    VERIFY_CFG['TIER1_CHECK_ONLY'] = False   # เดิมถูก set True ค้างถ้ารอบก่อนเลือก offline
    web_state_reset()                        # รีเซ็ตตัวนับ request / circuit breaker
    state._FUZZY_DICT_CACHE.clear()                # ล้าง fuzzy cache (กันผลค้างข้ามรอบ)
    try: state._PYTHAINLP_CACHE.clear()            # v6.1: ล้าง spell-cache ด้วย กันโตข้ามรอบใน session ยาว (Colab)
    except Exception: pass
    # [P1-FIX-STATECACHE] ล้าง lazy caches ใน state.py ด้วย — เดิมไม่ล้าง → ค้างข้ามรอบ
    #   ทั้งหมดเป็น cache ที่ rebuild ได้ (lazy-init guard มีอยู่ทุกจุดใช้งาน) → ล้างแล้วผลตรวจเหมือนเดิม
    #   build จาก CONSTRUCTION_DICT/CFG ที่เป็น static → rebuild ได้ค่าเดิมเป๊ะ (ไม่กระทบ determinism)
    state._CONSTRUCTION_DICT_BY_LEN = None
    state._PYTHAINLP_STEM_BLOCKLIST = None
    state._CAT_KEYWORDS = None
    state._PRODUCT_WHITELIST = None
    system_issues_reset()                    # v6.2: ล้าง audit trail (system issues) ของรอบก่อน กัน state bleed
    audit_text_num_reset()                   # v6: ล้าง log Text→ตัวเลข ของรอบก่อน
    if not _IN_NOTEBOOK:
        try: _CAPTURED_HTML.clear()          # ล้าง HTML buffer (เฉพาะโหมด VS Code/.py)
        except Exception: pass


def print_audit_banner():
    """พิมพ์ banner สรุป rules/fixes ต้นรอบ (side-effect: print). ไม่แตะ logic."""
    print('='*70)
    print('🧾 Invoice Audit System v8.1 — 52 Rules + 5 Specs + Analytics + ITM Upgrade')
    print('='*70)
    print(f'📋 Rules: {len(RULES)} กฎ')
    sev_count = Counter(r['severity'] for r in RULES.values())
    for sev in ['CRITICAL','ERROR','WARNING','INFO']:
        if sev in sev_count: print(f"   {SEVERITY_ICON[sev]} {sev}: {sev_count[sev]}")
    print(f'🔬 Product Verification 2-Tier: {"ON" if VERIFY_CFG["ENABLE"] else "OFF"}')
    print(f'🇹🇭 Thai Typo: {len(THAI_TYPO_PATTERNS)} patterns | Dict: {len(CONSTRUCTION_DICT)} คำ')
    print(f'🔧 PyThaiNLP: {"✅" if PYTHAINLP_AVAILABLE else "❌"}')
    print('─'*70)
    print(f'🆕 v5.8 fixes:')
    print(f'   [FIX-1] TAX001  : wider tax_id scan (no keyword required)')
    print(f'   [FIX-2] ADDR001 : ซอย fuzzy match + ซ. shorthand')
    print(f'   [FIX-3] BR001/2 : สแกนรหัสสาขาทั้ง block')
    print(f'   [FIX-4] NBSP    : อธิบาย NBSP/ZWS/BOM ใน detail')
    print(f'   [FIX-5] PyThaiNLP: partial whitelist + sim guard {CFG["PYTHAINLP_SIM_THRESHOLD"]}%')
    print(f'   [FIX-6] IV gap  : split severity (consecutive≥{CFG["IV_GAP_CRITICAL_RUN"]}=CRITICAL)')
    print(f'   [FIX-7] ITM001  : plausible discount detection ({CFG["DISCOUNT_MIN_PCT"]}-{CFG["DISCOUNT_MAX_PCT"]}%)')
    print(f'   [FIX-8] DT001   : รองรับ filename month range')
    print(f'   [FIX-9] ITM007  : skip ถ้าชื่อสั้นแต่ถูกต้อง (dict/keyword/spec)')


def parse_all_files(file_list):
    """parse ทุกไฟล์ (ห่อ try/except ต่อไฟล์ + gc/cache-trim เป็นช่วง). behavior 100% เดิม.
    Returns: (all_bills, filename_issues)."""
    print(f'\n📂 Parsing {len(file_list)} ไฟล์...')
    all_bills = []
    filename_issues = []
    _failed_files = []   # v6.1 FAILSAFE: เก็บรายชื่อไฟล์ที่อ่านไม่สำเร็จ เพื่อสรุปท้ายงาน
    _gc_every = max(1, int(CFG.get('GC_EVERY_N_FILES', 50)))   # v6.2 MEMORY: รอบ flush หน่วยความจำ
    for _fidx, fp in enumerate(tqdm(file_list, desc='Parsing'), 1):
        # [OBJ-OFFLINE/untrusted-input] กันไฟล์อันตราย (zip-bomb/ใหญ่ผิดปกติ) ก่อนแตะ parser
        #   ไฟล์ใบกำกับจริงผ่านทั้งหมด (limit กว้างพอ) → ไม่กระทบผล/golden hash ;
        #   ปฏิเสธเฉพาะไฟล์พยาธิสภาพ → บันทึก SYS001 + ข้าม (เหมือนไฟล์อ่านไม่สำเร็จ)
        _safe, _why = file_guard.inspect_file_safety(fp)
        if not _safe:
            _failed_files.append((os.path.basename(fp), _why))
            print(f'   ⛔ ข้ามไฟล์ {os.path.basename(fp)} (untrusted/ไม่ปลอดภัย): {_why}')
            log_system_issue('SYS001', 'Unsafe File Skipped', _why,
                             severity='ERROR', file=os.path.basename(fp), echo=False)
            continue
        # v6.1 FAILSAFE: ห่อการประมวลผล "ทั้งไฟล์" ไว้ใน try — ไฟล์เดียวพัง = ข้ามไฟล์นั้น
        #   ไม่ใช่ทำให้ทั้ง batch ล้ม (เดิม parse_filename / merge_continuation_bills /
        #   check_iv_format / check_filename_consistency อยู่นอก try → 1 ไฟล์เพี้ยน = เสียงานทั้งหมด)
        try:
            finfo = parse_filename(fp)
            bills = parse_file(fp)
            for b in bills: b['file_info'] = finfo
            all_bills.extend(bills)
            filename_issues.extend(check_filename_consistency(os.path.basename(fp), bills, finfo))
        except Exception as _fe:
            _failed_files.append((os.path.basename(fp), f'{type(_fe).__name__}: {str(_fe)[:120]}'))
            print(f'   ⚠️ ข้ามไฟล์ {os.path.basename(fp)} (อ่านไม่สำเร็จ): {type(_fe).__name__}: {str(_fe)[:120]}')
            # v6.2 OBSERVABILITY (TARGET 2): บันทึก file-level failure ลง audit trail ด้วย
            log_system_issue('SYS001', 'File Processing Failure',
                             'ประมวลผลไฟล์ล้มเหลว — ทั้งไฟล์ถูกข้าม',
                             severity='ERROR', file=os.path.basename(fp), exc=_fe, echo=False)
            continue
        finally:
            # v6.2 MEMORY (TARGET 1): คุม RAM ให้ "แบนราบ" ระหว่าง parse ไฟล์จำนวนมาก
            #   - ตัด cache ที่อาจโตไม่จำกัด (สะกดคำ/fuzzy-dict)
            #   - บังคับ gc เป็นช่วง ๆ → คืน DataFrame ชั่วคราว/ลด memory fragmentation
            #   ทั้งหมดนี้ "ผลตรวจเหมือนเดิม" (cache ตัดแล้ว recompute ได้, gc ไม่กระทบข้อมูล)
            if (_fidx % _gc_every) == 0:
                _trim_cache(_PYTHAINLP_CACHE, CFG.get('MAX_PYTHAINLP_CACHE', 50000))
                _trim_cache(_FUZZY_DICT_CACHE, CFG.get('MAX_FUZZY_DICT_CACHE', 50000))
                gc.collect()
    gc.collect()   # v6.2: เก็บกวาดรอบสุดท้ายหลัง parse ครบทุกไฟล์
    if _failed_files:
        print(f'\n⚠️ มี {len(_failed_files)} ไฟล์อ่านไม่สำเร็จ ถูกข้าม (บิลจากไฟล์อื่นยังประมวลผลครบ):')
        for _fn, _er in _failed_files[:20]:
            print(f'   • {_fn} — {_er}')
        if len(_failed_files) > 20:
            print(f'   ... และอีก {len(_failed_files)-20} ไฟล์')
    return all_bills, filename_issues


def run_all_rules(all_bills, master):
    """รัน 56 rules ต่อบิล (กันชนชั้นสุดท้ายต่อบิล). mutates all_bills in place. ไม่แตะ logic."""
    print(f'\n🛡️ Running {len(RULES)} rules...')
    unit_index = build_unit_index(all_bills)

    # v5.9 FIX-2: ส่ง all_bills ตรง ๆ เข้า run_rules แทนการฝังใน bill dict
    # (ลบ circular reference: เดิม bill แต่ละตัวแบก _all_bills_ref ซึ่งชี้กลับมาที่ list ตัวเอง)
    for b in tqdm(all_bills, desc='Validating'):
        try:
            run_rules(b, master, b.get('file_info', {}), unit_index=unit_index, all_bills_ref=all_bills)
        except Exception as _re:
            # v6: กันชนชั้นสุดท้าย — บิลเดียวพังต้องไม่ล้มทั้ง batch (match_company อยู่นอก try ภายใน run_rules)
            # v8.4 STABILITY: บิลที่ run_rules พังกลางคันจะยังไม่มี master_key/match_score → เติม default
            #   กัน KeyError ภายหลังตอน summarize/dashboard (ซึ่งอ่าน b['master_key'] ตรงๆ) = ไม่ให้ล้มทั้งรอบ
            b.setdefault('master_key', '(ไม่พบใน master)')
            b.setdefault('match_score', 0)
            log_system_issue('SYS001', 'Rule Engine Failure',
                             'run_rules ล้มทั้งบิล — ข้ามบิลนี้ (ไม่ล้มทั้ง batch)',
                             severity='ERROR', file=b.get('file',''), sheet=str(b.get('sheet','')),
                             exc=_re, echo=False)


# ===========================================================================
# ⭐ SINGLE SOURCE OF TRUTH — "ลำดับศักดิ์สิทธิ์" ของการตรวจหลัก (audit core)
# ---------------------------------------------------------------------------
# เดิมลำดับนี้ถูก "คัดลอกด้วยมือ" ไว้ 3 ที่ (main() / agents.orchestrator._run_audit_core /
# golden_master.py) → แก้ที่หนึ่งลืมอีกที่ = engine กับ agent เพี้ยนเงียบ ๆ, golden hash ดริฟต์
# โดยไม่มีใครรู้จนกว่าจะรัน regression. รวมเป็นฟังก์ชันเดียวตรงนี้ → ทุกเส้นเรียกตัวเดียวกัน
# → "engine == agent == golden" รับประกันด้วยโครงสร้าง ไม่ใช่ด้วยวินัยการก๊อป.
#
# แบ่ง 2 เฟสให้ตรงกับโครงสร้าง main() เป๊ะ (main แทรก "การแสดงผล" ไว้ระหว่างสองเฟส):
#   เฟส 1 = _audit_core_rules()      : dup → rules → iv/typos/summary  (ก่อนแดชบอร์ด)
#   เฟส 2 = _audit_core_crosschecks(): apply_iv_period + apply_sheet_date  (หลังแดชบอร์ด)
# เส้นที่ไม่มีการแสดงผลคั่น (orchestrator / golden_master) ใช้ run_audit_core() = เฟส1+เฟส2.
#
# byte-identical: บนชุดข้อมูล golden ทั้ง 3 ขั้นในเฟส1 "ไม่เคยโยน exception" → ใส่ try/except
# (error isolation) ไม่เปลี่ยนผลลัพธ์/ลำดับ → golden hash คงเดิม. ข้อความ console วิ่งผ่าน
# callback `log` → main คงพิมพ์เหมือนเดิมทุกบรรทัด, ส่วน orchestrator/golden_master เงียบเหมือนเดิม.
# ===========================================================================
def _audit_core_rules(all_bills, master, isolate=True, log=None):
    """เฟส 1 ของ audit core (ก่อนการแสดงผลใน main): ตรวจรายการซ้ำ → 56 rules →
    ลำดับ IV → คำสะกด → สรุปต่อบริษัท. mutate all_bills ในที่ (run_all_rules เติม issue).

    Args:
        all_bills:  list บิลที่ parse แล้ว (จะถูก mutate โดย run_all_rules)
        master:     master data ของบริษัท
        isolate:    True = ห่อ iv/typos/summary ด้วย try/except (P1-FIX-ISOLATION) แล้ว log SYS003
                    ถ้าพัง — งานที่เหลือยังออกครบ. False = ปล่อย exception ลอยขึ้น (ใช้ตอน debug).
        log:        callable(str) สำหรับข้อความ console (เช่น print). None = เงียบ.

    Returns:
        dict: {'dup_items','iv_seq','iv_date','iv_issues','typos','summary'}
              (iv_issues = iv_seq + iv_date — ค่าที่รายงานใช้; iv_seq/iv_date แยกไว้ให้ golden hash)
    """
    emit = log if callable(log) else (lambda _m: None)

    # --- ตรวจรายการสินค้าซ้ำ (PATCH4B) + พิมพ์สรุปแบบเดียวกับ main เดิม ---
    dup_items = check_duplicate_items(all_bills)
    if dup_items:
        emit(f'\n⚠️  PATCH4B: พบรายการซ้ำ {len(dup_items)} กลุ่ม (อาจ parse บิลซ้ำ):')
        for d in dup_items[:20]:
            emit(f"   • {d['ไฟล์']}/{d['ชีต']} IV:{d['IV']} — \"{d['รายการ']}\" "
                 f"ยอด {d['ยอด']} ซ้ำ {d['พบซ้ำ']} ครั้ง (ลำดับ {d['ลำดับ']})")
        if len(dup_items) > 20:
            emit(f'   ... และอีก {len(dup_items)-20} กลุ่ม')
    else:
        emit('✅ PATCH4B: ไม่พบรายการสินค้าซ้ำ')

    # --- 56 rules (พิมพ์ banner/tqdm ของตัวเองอยู่แล้ว — ไม่ผ่าน emit, พฤติกรรมเดิม) ---
    run_all_rules(all_bills, master)

    # --- cross-bill checks: ห่อแยกตาม isolate flag (semantics ตรงกับ main เป๊ะ) ---
    if isolate:
        # main ห่อ (check_invoice_sequence + check_iv_date_sequence) ไว้ใน try เดียว →
        # ถ้าตัวใดตัวหนึ่งพัง iv_issues ว่างทั้งคู่. ที่นี่รักษา semantics นั้น (both → []).
        try:
            iv_seq = check_invoice_sequence(all_bills)
            iv_date = check_iv_date_sequence(all_bills)
        except Exception as _ve:
            iv_seq, iv_date = [], []
            emit(f'   ⚠️ IV sequence check ล้มเหลว — ข้ามส่วนนี้: {type(_ve).__name__}: {str(_ve)[:120]}')
            log_system_issue('SYS003', 'IV Sequence Check Failure',
                             'ตรวจลำดับ IV ล้มเหลว — ข้ามผลส่วนนี้ (บิล/กฎอื่นยังครบ)',
                             severity='ERROR', exc=_ve, echo=False)
        try:
            typos = check_product_typos(all_bills)
        except Exception as _ve:
            typos = []
            emit(f'   ⚠️ Product typo check ล้มเหลว — ข้ามส่วนนี้: {type(_ve).__name__}: {str(_ve)[:120]}')
            log_system_issue('SYS003', 'Product Typo Check Failure',
                             'ตรวจคำสะกดสินค้าล้มเหลว — ข้ามผลส่วนนี้ (บิล/กฎอื่นยังครบ)',
                             severity='ERROR', exc=_ve, echo=False)
        try:
            summary = summarize_by_company(all_bills)
        except Exception as _ve:
            summary = {}
            emit(f'   ⚠️ Summary ล้มเหลว — ใช้ค่าว่าง: {type(_ve).__name__}: {str(_ve)[:120]}')
            log_system_issue('SYS003', 'Summary Failure',
                             'สรุปต่อบริษัทล้มเหลว — ใช้ค่าว่าง (บิล/กฎยังครบ)',
                             severity='ERROR', exc=_ve, echo=False)
    else:
        iv_seq = check_invoice_sequence(all_bills)
        iv_date = check_iv_date_sequence(all_bills)
        typos = check_product_typos(all_bills)
        summary = summarize_by_company(all_bills)

    return {
        'dup_items': dup_items,
        'iv_seq': iv_seq,
        'iv_date': iv_date,
        'iv_issues': iv_seq + iv_date,   # ← ค่าที่ Report/dashboard ใช้ (ตรงกับ main เดิม)
        'typos': typos,
        'summary': summary,
    }


def _audit_core_crosschecks(all_bills):
    """เฟส 2 ของ audit core (หลังการแสดงผลใน main): cross-check ที่ "เติม issue ลงบิล".
    ต้องรัน *หลัง* summary และ *ครั้งเดียว* (เรียกซ้ำ = issue ซ้ำ → golden hash เปลี่ยน)."""
    apply_iv_period_crosscheck(all_bills)    # DT004: วันที่ vs งวดในเลข IV
    apply_sheet_date_crosscheck(all_bills)   # DOC001: วันที่ vs ชื่อชีต


def run_audit_core(all_bills, master, isolate=True, log=None):
    """ลำดับศักดิ์สิทธิ์เต็ม = เฟส1 + เฟส2 (ไม่มีการแสดงผลคั่น).

    ใช้โดยเส้นที่ไม่ต้องแทรกแดชบอร์ดระหว่างเฟส: agents.orchestrator และ golden_master.
    คืน dict เดียวกับ _audit_core_rules (เพิ่มการันตีว่า crosscheck ถูกรันแล้ว 1 ครั้ง)."""
    result = _audit_core_rules(all_bills, master, isolate=isolate, log=log)
    _audit_core_crosschecks(all_bills)
    return result


def _emit_agent_notepad(master, file_list, all_bills, core_result, out_path, filename_issues):
    """[v9.1+ ADVISORY] ออกไฟล์ "รายงานสรุปการทำงานของ agent" (agent_report.txt) ข้าง Excel.

    ★ ทำไมปลอดภัย/เร็ว (เสี่ยงศูนย์ ต่อผลตรวจหลัก):
      - reuse บิลที่ "parse + ตรวจ (rules+crosscheck) เสร็จแล้ว" ในหน่วยความจำ → ไม่ parse ซ้ำ
        (ImportAgent/รันกฎไม่ถูกเรียกอีก) → เพอร์ฟอร์แมนซ์ parse ไม่ตก
      - รันเฉพาะ agent ชั้น "อ่านอย่างเดียว" (review/tier2/ai/synthesis/super) → ไม่ mutate bills,
        ไม่ rerun กฎ/crosscheck (กัน issue ซ้ำ) → ผลตรวจ/Excel/golden hash ไม่เปลี่ยน
      - ห่อ try/except ทุกชั้น: เลเยอร์ agent มีปัญหาใด ๆ → ข้ามเงียบ ไม่ล้มงานหลัก
        (Excel ถูกเขียนเสร็จก่อนเรียกฟังก์ชันนี้เสมอ — ไฟล์ผลลัพธ์หลักจึงปลอดภัย 100%)

    core_result : dict จาก _audit_core_rules/run_audit_core (มี iv_seq/iv_date/iv_issues/typos/
                  summary/dup_items) — เติมลง PipelineContext ให้ตรงกับที่ orchestrator เติมเอง
    out_path    : พาธไฟล์ Excel ที่เพิ่งเขียน (ใช้หา report_dir + อ้างอิงในรายงาน)
    """
    # ให้เลเยอร์ agent ใช้ "โมดูลที่กำลังรันอยู่" เป็น core (กันการ import ไฟล์หลักซ้ำเป็นสำเนาที่ 2)
    #   รันตรง: __name__ == '__main__' → core_access import __main__ (โมดูลเดียวกับที่รัน main นี้)
    #   ถูก import: __name__ == ชื่อโมดูล → ใช้สำเนาที่โหลดแล้ว. ทั้งสองเคสไม่รันไฟล์หลักซ้ำ.
    os.environ.setdefault('PUKPUI_MAIN_MODULE', __name__)
    try:
        from agents.contracts import PipelineContext
        from agents.orchestrator import run_pipeline_advisory
    except Exception as _e:
        print(f'   ℹ️ ข้ามรายงานการทำงาน agent (โหลดเลเยอร์ agent ไม่ได้: '
              f'{type(_e).__name__}: {str(_e)[:120]})')
        return
    try:
        cr = core_result or {}
        report_dir = os.path.dirname(os.path.abspath(out_path))
        ctx = PipelineContext(
            master=master or {},
            file_list=list(file_list or []),
            options={'report_dir': report_dir, 'write_report': False, 'write_note': True},
            bills=all_bills,
            filename_issues=list(filename_issues or []),
            iv_issues=cr.get('iv_issues', []),
            iv_seq=cr.get('iv_seq', []),
            iv_date=cr.get('iv_date', []),
            typos=cr.get('typos', []),
            summary=cr.get('summary', {}),
            dup_items=cr.get('dup_items', []),
            report_path=os.path.abspath(out_path),
        )
        run_pipeline_advisory(ctx, logger=None)   # เงียบ — ไม่รบกวน log หลัก
        _np = ctx.results.get('notepad')
        _path = (_np.summary or {}).get('path') if _np else None
        if _path:
            print(f'📝 รายงานการทำงาน Agent (Notepad) → {os.path.abspath(_path)}')
        else:
            print('   ℹ️ สร้างรายงานการทำงาน agent แล้ว (ไม่ได้เขียนไฟล์)')
    except Exception as _e:                         # ADVISORY: ห้ามล้มงานหลักเด็ดขาด
        print(f'   ⚠️ ข้ามรายงานการทำงาน agent — {type(_e).__name__}: {str(_e)[:140]}')


def main():
    reset_run_state()
    print_audit_banner()

    master = input_master_data()
    if not master: print('❌ ไม่มี master'); return
    print(f'\n✅ Master: {len(master)} บริษัท')
    run_self_check(master)                   # v6: ตรวจ master JSON ก่อนเริ่มตรวจบิล

    print('\n' + '='*70)
    print('เลือกวิธีรับไฟล์:\n  1. โฟลเดอร์ปัจจุบัน (โฟลเดอร์ที่รันสคริปต์)\n  2. ระบุ path โฟลเดอร์เอง')
    choice = input('เลือก [1/2] (default=1): ').strip() or '1'

    file_list = []
    if choice == '2':
        try:
            file_list = get_files_via_upload()   # จะถาม path ให้พิมพ์เอง
        except Exception as e: print(f'⚠️ {e}'); return
    else:
        try:
            file_list = get_files_via_drive('.')
            print(f'📂 พบ {len(file_list)} ไฟล์ใน "{os.path.abspath(".")}"')
        except Exception as e: print(f'⚠️ {e}'); return

    if not file_list: print('❌ ไม่มีไฟล์'); return

    all_bills, filename_issues = parse_all_files(file_list)

    # === v6.2 OBSERVABILITY: สรุป + บันทึก audit trail ของ parse failure (sidecar) ===
    if state._SYSTEM_ISSUES:
        _by_code = Counter(i.get('code', 'SYS001') for i in state._SYSTEM_ISSUES)
        print(f'\n🩺 System issues (ตามรอยได้): {len(state._SYSTEM_ISSUES)} รายการ — '
              + ', '.join(f'{c}×{n}' for c, n in _by_code.items()))
        _logp = flush_system_issues_to_disk()
        if _logp:
            print(f'   📝 บันทึก audit trail → {os.path.abspath(_logp)}')
    else:
        print('\n🩺 System issues: ไม่มี (parse ครบทุกไฟล์/ชีตที่อ่านได้)')

    if not all_bills: print('❌ ไม่พบบิล'); return
    print(f'✅ พบ {len(all_bills)} บิล')

    # === คำนวณ parse confidence ทุกบิล (ใช้ในการแสดง low-confidence) ===
    for b in all_bills:
        compute_bill_confidence(b)

    # === PATCH4B (รายการซ้ำ) + 56 rules + IV/typo/summary ===
    #   เรียก "audit core เฟส 1" จุดเดียว (โค้ดจริง + ข้อความ + การ isolate อยู่ใน _audit_core_rules)
    #   log=print → main คงพิมพ์ทุกบรรทัดเหมือนเดิม. เส้น agent/golden ใช้ตัวเดียวกันแต่ log เงียบ.
    _core = _audit_core_rules(all_bills, master, isolate=True, log=print)
    _dup_items = _core['dup_items']
    iv_issues  = _core['iv_issues']
    typos      = _core['typos']
    summary    = _core['summary']

    display_executive_dashboard(all_bills, summary, iv_issues, typos, filename_issues, len(file_list))

    # === แสดงบิลที่ระบบอ่านไม่ชัด ต้องเช็คด้วยมือ ===
    display_low_confidence_bills(all_bills)

    # === v6: สรุป Text→ตัวเลข ที่ระบบกู้คืน (ความโปร่งใส) ===
    audit_text_num_summary(echo=True)

    # 📁 โฟลเดอร์ปลายทางสำหรับเก็บไฟล์รีพอร์ต  ←★ "จุดเดียว" ที่กำหนด path ปลายทางของรีพอร์ตทั้งหมด
    #   ค่าเริ่มต้น (v9): เก็บที่เดสก์ท็อป โฟลเดอร์ "รีพอร์ต" — ถ้ายังไม่มีโฟลเดอร์นี้ ระบบจะสร้างให้อัตโนมัติ
    #   อยากเปลี่ยนที่เก็บ: แก้ path ในเครื่องหมายคำพูดบรรทัด REPORT_DIR ด้านล่าง (ใช้ r'...' เสมอ กัน \ ใน path เพี้ยน)
    #   หรือ (ไม่ต้องแก้โค้ด) ตั้ง environment variable PUKPUI_REPORT_DIR ทับเป็นรายครั้งก็ได้
    REPORT_DIR = os.environ.get('PUKPUI_REPORT_DIR') or r'C:\Users\User\Desktop\รีพอร์ต'
    try:
        os.makedirs(REPORT_DIR, exist_ok=True)   # ถ้ายังไม่มีโฟลเดอร์ จะสร้างให้อัตโนมัติ
    except Exception as _e:                       # v8.4 STABILITY: path เขียนไม่ได้ (คนละ user/OS/สิทธิ์) → อย่าล้มทั้งรอบหลังประมวลผลเสร็จ
        REPORT_DIR = os.getcwd()
        print(f'⚠️ สร้างโฟลเดอร์รายงานไม่ได้ ({type(_e).__name__}) → บันทึกที่โฟลเดอร์ปัจจุบันแทน: {REPORT_DIR}')
    out = os.path.join(REPORT_DIR, f'audit_v58_{datetime.now().strftime("%Y%m%d_%H%M%S")}.xlsx')

    # PATCH 1+2: cross-checks — เรียก "audit core เฟส 2" จุดเดียว (behavior 100% เดิม)
    _audit_core_crosschecks(all_bills)       # DT004 (วันที่ vs งวดในเลข IV) + DOC001 (วันที่ vs ชื่อชีต)

    if LEAN_REPORT:
        # ---------- โหมดคลีน: 7 ชีต + แดชบอร์ดในตัว ----------
        print('\n📊 สร้างรายงานแบบคลีน (Executive)...')
        if build_clean_report(all_bills, summary, iv_issues, typos, filename_issues, out):
            try:
                display(HTML(f'<div style="background:#1F2A37;color:white;padding:24px;border-radius:10px;text-align:center;margin:20px 0;border-top:2px solid #B08D57;"><div style="font-size:18px;font-weight:600;">✅ รายงาน (คลีน) สำเร็จ</div><div style="font-size:14px;margin-top:8px;opacity:0.85;">{out}</div></div>'))
            except Exception: pass
            print(f'\n✅ ไฟล์รายงาน (คลีน 7 ชีต) บันทึกแล้ว → {os.path.abspath(out)}')
            print('   ชีต: Dashboard | Summary | ทุกบิล | รายการสินค้า | Error Report | High Risk | บิลซ้ำ')
            # [v9.1+] ออกไฟล์รายงานการทำงานของ agent (.txt) ข้าง Excel — advisory, reuse บิลในหน่วยความจำ
            _emit_agent_notepad(master, file_list, all_bills, _core, out, filename_issues)
        else:
            print('❌ สร้างรายงานคลีนไม่สำเร็จ')
    else:
        # ---------- โหมดเต็ม: ทุกชีต + addon + verification + analytics ----------
        if export_excel(all_bills, summary, iv_issues, typos, filename_issues, out):
            run_addon_pack(all_bills, out)
            if VERIFY_CFG['ENABLE']:
                print('\n' + '='*70)
                # v9 [STABILITY-FIX]: เดิมเรียก input() ตรง ๆ → ค้าง/พังด้วย EOFError
                #   เมื่อรันแบบไม่โต้ตอบ (CI/cron/subprocess/redirect). ทำให้ปลอดภัย:
                #     1) env PUOPUY_ONLINE_VERIFY = 1/0/y/n → ใช้ค่านั้น (ไม่ถาม)
                #     2) ไม่มี TTY (อัตโนมัติ) → default ออฟไลน์ (ไม่ค้าง)
                #     3) มี TTY → ถามตามเดิม; กด Ctrl-D/EOF → ออฟไลน์
                _env_ov = (os.environ.get('PUOPUY_ONLINE_VERIFY', '') or '').strip().lower()
                if _env_ov in ('1', 'y', 'yes', 'true', 'on'):
                    use_online = True
                elif _env_ov in ('0', 'n', 'no', 'false', 'off'):
                    use_online = False
                elif not sys.stdin or not sys.stdin.isatty():
                    print('   (ไม่มี TTY — ข้าม online search อัตโนมัติ; ตั้ง PUOPUY_ONLINE_VERIFY=1 ถ้าต้องการ)')
                    use_online = False
                else:
                    try:
                        use_online = input('ใช้ Tier 2 (online search)? [Y/n]: ').strip().lower() != 'n'
                    except EOFError:
                        use_online = False
                results = run_product_verification(all_bills, enable_online=use_online)
                if results and export_verification_to_excel(results, out):
                    display(HTML(f'<div style="background:linear-gradient(135deg,#7C3AED,#5B21B6);color:white;padding:20px;border-radius:10px;text-align:center;margin:16px 0;"><div style="font-size:16px;font-weight:600;">🔬 Product Verification เสร็จสิ้น</div><div style="font-size:13px;margin-top:6px;opacity:0.9;">{len(results)} รายการ → ดูชีต "Product Verification" ใน Excel</div></div>'))

            display(HTML(f'<div style="background:linear-gradient(135deg,#16A34A,#15803D);color:white;padding:24px;border-radius:10px;text-align:center;margin:20px 0;box-shadow:0 6px 16px rgba(22,163,74,0.25);"><div style="font-size:18px;font-weight:600;">✅ Export สำเร็จ</div><div style="font-size:14px;margin-top:8px;opacity:0.9;">{out}</div></div>'))
            print(f'\n✅ ไฟล์ผลลัพธ์ Excel บันทึกแล้ว → {os.path.abspath(out)}')
            # [v9.1+] ออกไฟล์รายงานการทำงานของ agent (.txt) ข้าง Excel — advisory, reuse บิลในหน่วยความจำ
            _emit_agent_notepad(master, file_list, all_bills, _core, out, filename_issues)

            if ANALYTICS_CFG['ENABLE']:
                print('\n' + '='*70)
                print('📊 ANALYTICS MODULE')
                print('='*70)
                if input('รัน Anomaly Dashboard (Plotly)? [Y/n]: ').strip().lower() != 'n':
                    try:
                        run_analytics(excel_path=out)
                    except Exception as e:
                        print(f'⚠️ Analytics fail: {e}')
                        traceback.print_exc()



# ============================================================
# 🎁 v5.8q ADD-ON PACK — 7 Features for Accountants (Additive)
# ============================================================
# วิธีใช้: paste บล็อกนี้ "ต่อท้าย" โค้ดหลัก v5.8 ทั้งหมด
#         แล้วเรียก run_addon_pack(all_bills, out_excel_path) หลัง export_excel
#
# ฟีเจอร์:
#   1. DUP001 - Duplicate Bill Detection (บิลซ้ำ)
#   2. WHT001 - Withholding Tax 3% Check (ภงด.53)
#   3. RND001 - Round Number Anomaly (ยอดปัดสวยผิดปกติ)
#   4. PER001 - Period Coverage Analysis (ความครบของงวด)
#   5. VND001 - Vendor Risk Profile (โปรไฟล์ความเสี่ยงคู่ค้า)
#   6. BNF001 - Benford's Law Digit Distribution (ตรวจหลอกแบบสถิติ)
#   7. Audit Trail Sheet (บันทึกการตรวจ + auto-fix)
#
# ไม่กระทบ:
#   - ไม่แก้ RULES dict
#   - ไม่แก้ฟังก์ชัน parse / rules / cross-bill เดิม
#   - เป็นการ "อ่าน" บิลที่ parse แล้วเพื่อสร้างชีตเพิ่มใน Excel
# ============================================================

import math
from collections import defaultdict, Counter




















# ============================================================
# 📍 วิธีเรียกใช้ — เพิ่ม 1 บรรทัดใน main() หลัง export_excel
# ============================================================
#
# ในฟังก์ชัน main() หา:
#     if export_excel(all_bills, summary, iv_issues, typos, filename_issues, out):
#
# หลังบล็อกนั้น (อาจหลัง verification หรือก่อน analytics) เพิ่ม:
#     run_addon_pack(all_bills, out)
#
# หรือถ้าอยากเรียก standalone (รัน addon ทีหลัง):
#     run_addon_pack(all_bills, 'audit_v58_xxxxx.xlsx')
# ============================================================


# ============================================================
# v8.2 FIX: เติม entry point กลับ — ตอนต่อโค้ด addon ท้ายไฟล์ บล็อกนี้หายไป
#   ทำให้รัน `python ไฟล์.py` แล้วโปรแกรม "ไม่ทำงาน" (นิยามฟังก์ชันครบแล้วจบ)
#   (import ไฟล์นี้จะไม่สั่งรัน main เพื่อให้ reuse/unit test ได้)
# ============================================================
if __name__ == '__main__':
    try: main()
    except KeyboardInterrupt: print('\n⏹️ ยกเลิก')
    except Exception as e:
        print(f'\n❌ Error: {e}'); traceback.print_exc()
