# -*- coding: utf-8 -*-
"""pukpui_modular_base — [SPLIT #3 slice-1] shared scope ของ monolith
รวม imports (จาก leaf modules) + ค่าคงที่ + CONSTRUCTION_DICT + setup ทั้งหมด
แยกออกจาก ปุ้มปุ้ย_ultimate_v9_modular.py แบบ verbatim (ผลเดิม 100%; golden ยืนยัน).
top + slice ฟังก์ชัน import จากที่นี่แบบ explicit (zero-star).
"""
# -*- coding: utf-8 -*-
"""ปุ้มปุ้ย 03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oybEpD7v6df_Ewdvpq3uu6IN7DZpV1aj
"""

# ============================================================
# 🔒 LOCKED DEPENDENCIES — เวอร์ชันที่ผ่านการทดสอบ (Python 3.12)
#    ทดสอบล่าสุด: ใช้งานได้ครบทุกตัว
#    ⚠️ ถ้าวันใด pip install ตัวใดตัวหนึ่ง error → Colab อาจเปลี่ยน Python
#       ให้ดู LOCK CHECK ด้านล่างว่าเวอร์ชันไหนเพี้ยน
# ============================================================
# 📦 VS Code: ติดตั้งครั้งเดียวจาก Terminal (อย่ารันในไฟล์นี้):
#     pip install -r requirements.txt
#   หรือ:
#     pip install pandas==2.2.2 xlrd==2.0.1 openpyxl==3.1.5 rapidfuzz==3.10.1 \
#                 matplotlib==3.9.2 plotly==5.24.1 tqdm==4.67.1 pythainlp==5.0.5
# (บรรทัด !pip ของ Colab ถูกตัดออก เพราะใช้กับไฟล์ .py ปกติไม่ได้)
# ============================================================


# ============================================================
# 🧾 Invoice & Tax Document Audit System v5.8
# 41 Rules + Thai Typo + 2-Tier Verification + 5 Numerical Specs + Analytics
# ============================================================
# v5.8 fixes (จาก v5.7):
#  [FIX-1] TAX001  : wider tax_id scan (no keyword required) + Excel numeric cells
#  [FIX-2] ADDR001 : ซอย fuzzy match + normalize '/' + รองรับ ซ.
#  [FIX-3] BR001/2 : สแกนรหัสสาขา/สนญ. ทั้ง block ไม่จำกัดแค่ company name line
#  [FIX-4] NBSP    : อธิบาย NBSP/ZWS/BOM ใน detail message
#  [FIX-5] PyThaiNLP: partial whitelist (stem in CONSTRUCTION_DICT → skip)
#                     + similarity guard 75→80
#  [FIX-6] IV gap  : split severity (≥3 consecutive=CRITICAL, ไม่งั้น=WARNING)
#  [FIX-7] ITM001  : ตรวจ plausible discount → skip flag (1-50% ส่วนลด=legit)
#  [FIX-8] DT001   : รองรับ filename month range "69.03-04"
#  [FIX-9] ITM007  : ชื่อสั้น+อยู่ใน CONSTRUCTION_DICT/category keywords → skip
# ============================================================
# 🛡️ v6.1 STABILITY HARDENING (ไม่เพิ่มฟีเจอร์ — แก้ความเสถียร/กันพังเท่านั้น;
#    business logic เดิมคงไว้ 100%, ผลตรวจบิลที่อ่านได้เหมือนเดิมทุกประการ):
#  [S1-CRITICAL] main() parsing loop : ห่อ try/except ต่อไฟล์ — 1 ไฟล์เพี้ยน = ข้าม
#                ไฟล์นั้น ไม่ใช่ล้มทั้ง batch (เดิม parse_filename / merge_continuation_bills /
#                check_iv_format / check_filename_consistency อยู่นอก try → เสียงานทั้งหมด)
#  [S2-CRITICAL] parse_file()        : ปิด ExcelFile ใน finally — กัน file-handle/RAM รั่ว
#                ตอนวนอ่านไฟล์จำนวนมาก (เดิมไม่เคยปิด → เสี่ยง OSError: Too many open files)
#  [S3-MEDIUM]   TOR item builder    : เพิ่มคีย์ 'name_raw' ให้ schema เท่า parser หลัก
#  [S3-MEDIUM]   ITM004 (r_itm004)   : อ่าน name_raw แบบ .get() — เดิม KeyError บนบิล TOR
#                ทำให้กฎตรวจคำสะกด/อักขระแปลกถูกข้ามเงียบทุกบิล TOR (สูญเสียการตรวจ)
#  [S5-LOW]      main()              : เคลียร์ _PYTHAINLP_CACHE ตอนเริ่มรอบด้วย กันโตข้ามรอบ
# ============================================================
# 🎨 v6.3 REPORT POLISH (เฉพาะรายงานคลีน — ไม่แตะ business logic/ผลตรวจ):
#  - แถบหัวเรื่องสไตล์ผู้บริหาร (ดำ+เส้นแดง+ซับไตเติล) ทุกชีตข้อมูล
#  - เส้น accent แดงใต้หัวตาราง + แท็บชีตสีตามประเภท (หาง่าย ดูมือโปร)
#  - ตรึงคอลัมน์ระบุไฟล์ (บริษัท/ไฟล์/IV) ในชีต 'รายการสินค้า'/'ทุกบิล'
#    → เลื่อนตารางไปขวาแล้วยังเห็นว่าบรรทัดนั้นมาจากไฟล์ไหน
#  หมายเหตุ: คอลัมน์ 'ไฟล์' มีอยู่แล้วในชีตรายการสินค้า/ทุกบิล/Error Report
#  (รายงานคลีนไม่ถูกอ่านกลับโดย analytics → ปรับหน้าตาได้ปลอดภัย)
# ============================================================
# 🎨 v6.4 MINIMAL RESTYLE (เฉพาะหน้าตารายงานคลีน — โครงสร้าง/คอลัมน์/ข้อมูล/ผลตรวจ
#    เหมือนเดิม 100%, เปลี่ยนเฉพาะ "สไตล์" ให้เรียบหรู สมผู้บริหาร):
#  - palette ใหม่: ดำสนิท→ถ่านสเลตสุภาพ (#1F2A37), แดงสด Tesla (#E82127)→
#    ใช้สีเฉพาะระดับความรุนแรงแบบหม่น (อิฐ/ส้มเอิร์ธ/เขียว/น้ำเงิน)
#  - เส้น accent: แดงหนา (medium/3-4px) → ทองหม่นบางๆ (#B08D57 thin/2px) จุดเดียว
#  - ตัวอักษรเนื้อหานุ่มขึ้น (#3F4A5A) + ซับไตเติลเทาคูล — อ่านสบายตา
#  - คงทุกอย่าง: 7 ชีต, ตรึงคอลัมน์, ฟิลเตอร์, แถวสรุป, สีแท็บ, รูปแบบตัวเลข
# รันใน VS Code ได้เลย:  python audit_v58_vscode.py

# ============================================================
# 🔧 v9 INTEGRITY + ACCURACY (รวมแพตช์ — ตรวจสอบกับไฟล์จริง 75 ไฟล์/580 บิล:
#     regression=0 ยอดเงินทุกบิลเท่าเดิม | system issues=0 | bills เท่าเดิม)
#  [P0][FIX-1] _pb_finalize_amounts(): ติด provenance ('ocr'|'derived'|'item_sum')
#              ให้ยอด subtotal/vat/total — ไม่เปลี่ยนพฤติกรรมการเติมยอดเดิม
#              + กฎใหม่ VAT010: ยอดที่ "ระบบคำนวณเอง" จะไม่ถูกถือว่าผ่าน VAT001/002/003
#              เงียบ ๆ (false-clean) แต่ตีกลับให้คนตรวจยอด VAT บนเอกสาร (58% ของบิล)
#  [P2][FIX-2] _kw_in_name(): กัน substring คำสั้นกำกวมใน ITM005 ('สี' ใน 'สี่'/'ทาสี')
#  [P2][FIX-3] CONSTRUCTION_DICT += 'แผ่นตัด' (คนละสินค้ากับ 'แผ่นขัด') แก้ ITM011 FP
#  [P2][FIX-4] ITM010: เลิกข้อความ 'ผิด -> ถูก -> ผิด' ที่ซ้ำซ้อน (การตรวจเดิมถูกต้อง)
# ============================================================


import state
import os, traceback, gc   # [prune dead-import] เดิม: re,glob,json,unicodedata,statistics ไม่ถูกใช้ใน monolith แล้ว (ย้ายไป leaf)
# [prune dead-import] urllib (parse/request) ไม่ถูกใช้ใน monolith แล้ว (network อยู่ webverify)
import file_guard   # [OBJ-OFFLINE] guard ไฟล์อินพุต untrusted (zip-bomb/resource) ก่อน parse
from datetime import datetime   # [prune dead-import] เดิม: timedelta,timezone ไม่ถูกใช้แล้ว
from collections import Counter   # [prune] defaultdict ไม่ถูกใช้ใน monolith
try:
    import xlrd                       # v8.2: ใช้เฉพาะอ่านไฟล์ .xls (เก่า) — ไม่มีก็รัน .xlsx ได้ปกติ ไม่ crash ตอน import
except ImportError:
    xlrd = None
try:
    from rapidfuzz import fuzz  # noqa: F401  import-as-dependency-gate: ขาด rapidfuzz → SystemExit (ข้อความชัด); fuzz ตัวจริงใช้ใน leaf layer
except ImportError:
    raise SystemExit('❌ ต้องติดตั้ง rapidfuzz ก่อนรัน:  pip install rapidfuzz')
try:
    from tqdm import tqdm
except ImportError:                   # v8.2: ไม่มีก็รันได้ (แค่ไม่มีแถบ progress)
    def tqdm(iterable=None, *args, **kwargs):
        return iterable if iterable is not None else iter(())
try:
    import matplotlib
    matplotlib.use('Agg')          # VS Code: ไม่มีหน้าต่าง GUI ของ Jupyter → ใช้ backend แบบเซฟไฟล์
    import matplotlib.pyplot as plt
except ImportError:
    # v9.1 [FINDING-1]: matplotlib เป็นชั้นแสดงผล (version_gate จัดเป็น "degrade ได้/WARN")
    #   แต่เดิม import แบบแข็ง → ขาดแล้ว crash ตอน import ขัดกับสิ่งที่ gate บอก.
    #   ทำให้ optional แบบเดียวกับ reporting.py (plt=None) → audit รันได้ ไม่มี dashboard เท่านั้น.
    plt = None

# ============================================================
# 🖥️ VS Code COMPAT SHIM — แทน IPython.display ของ Colab/Jupyter
#   ใน Colab: display(HTML(...)) จะแสดงผลในเซลล์
#   ใน VS Code (.py ธรรมดา): ไม่มีตัวแสดงผล → เก็บ HTML ทั้งหมดไว้
#   แล้วเขียนเป็นไฟล์ audit_dashboard_report.html ตอนจบโปรแกรม (เปิดด้วยเบราว์เซอร์)
# ============================================================
try:
    from IPython.display import display, HTML          # ถ้าเผลอรันใน Jupyter ก็ยังใช้ได้
    _IN_NOTEBOOK = True
except Exception:
    _IN_NOTEBOOK = False
    _CAPTURED_HTML = []

    class HTML:                                          # ตัวแทน HTML object
        def __init__(self, data=''):
            self.data = data

    def display(obj=None, *args, **kwargs):              # ตัวแทน display()
        if obj is None:
            return
        data = getattr(obj, 'data', None)
        if data is not None:
            _CAPTURED_HTML.append(str(data))             # เก็บไว้เขียนไฟล์ทีหลัง
        else:
            print(obj)

    import atexit
    def _dump_html_report():
        if not _CAPTURED_HTML:
            return
        out = 'audit_dashboard_report.html'
        try:
            with open(out, 'w', encoding='utf-8') as f:
                f.write('<!DOCTYPE html><html lang="th"><head><meta charset="utf-8">'
                        '<meta name="viewport" content="width=device-width,initial-scale=1">'
                        '<title>Audit Dashboard v5.8</title>'
                        '<style>body{font-family:"Noto Sans Thai",-apple-system,Segoe UI,'
                        'Tahoma,sans-serif;background:#F8FAFC;margin:0;padding:24px;}</style>'
                        '</head><body>')
                f.write('\n'.join(_CAPTURED_HTML))
                f.write('</body></html>')
            print(f'\n🖥️  Dashboard (HTML) บันทึกแล้ว → {os.path.abspath(out)}')
            print('    เปิดไฟล์นี้ด้วยเบราว์เซอร์เพื่อดู Executive Dashboard')
        except Exception as e:
            print(f'⚠️ เขียน dashboard HTML ไม่ได้: {e}')
    atexit.register(_dump_html_report)

# [prune dead-import] openpyxl (load_workbook/styles/utils) ย้ายไป reporting/analytics แล้ว — monolith ไม่ใช้
import warnings
# [prune dead-import] decimal ใช้ผ่าน _D (puopuy_units) — monolith ไม่อ้าง Decimal/ROUND_HALF_UP ตรง
warnings.filterwarnings('ignore')
if plt is not None:                       # v9.1 [FINDING-1]: guard เมื่อ matplotlib ขาด (plt=None)
    plt.rcParams['font.family'] = 'DejaVu Sans'

# [P-DAG พาส2b] PyThaiNLP import guard → thai_text.py (main ได้ PYTHAINLP_AVAILABLE จาก re-export)


# --- slice 1: static config & constants extracted to config.py ---
from config import LEAN_REPORT, SEVERITY_ICON, THAI_TYPO_PATTERNS, audit_today   # [de-star P1] เดิม `import *` (ANALYTICS_CFG/APP_VERSION←reporting, CFG←validators, CONSTRUCTION_DICT/VERIFY_CFG←webverify; audit_today re-export ให้ agent lens ผ่าน core.get)
from puopuy_core import clean_tax_id, _taxid_checksum_ok   # [prune] เหลือเฉพาะ contract (core_access bind ตรง); เดิม re-export 9 ชื่อ ไม่ถูกใช้/ไม่อยู่สัญญา
# [prune dead-import] puopuy_dates (parse_date_any/_ivp_*) ไม่ถูกใช้ใน monolith + ไม่อยู่สัญญา (ใช้ผ่าน parser/validators layer)
from puopuy_units import _D, _vat_tolerance   # [prune] เหลือเฉพาะ contract (core_access bind ตรง); extract_unit_hint/_unit_canon ไม่ถูกใช้
from rules_engine import match_company, run_rules   # [de-star P1] เดิม `import *` (RULES bind จาก reporting-import; เป็น object เดียวกัน)
from diagnostics import _trim_cache, flush_system_issues_to_disk, system_issues_reset   # [de-star P1] เดิม `import *` (log_system_issue bind จาก validators-import ด้านล่าง)
# [de-star P1] เดิม `from thai_text import *` — ลบทิ้ง: bareword เดียวที่ monolith ใช้คือ
#   PYTHAINLP_AVAILABLE (บรรทัด print ด้านล่าง) ซึ่ง bind มาจาก `from reporting import (...)`
#   (reporting re-export จาก thai_text — ค่าเดียวกัน). thai_text fns อื่นใช้ผ่าน rules/parser layer
#   *coupling note:* ถ้าลบ PYTHAINLP_AVAILABLE จาก reporting-import ต้องเพิ่มกลับที่นี่
from parser import (   # [de-star P1] เดิม `import *` — explicit (data-extraction layer; 6 ชื่อ = bareword∪contract)
    audit_text_num_reset, audit_text_num_summary,
    get_files_via_drive, get_files_via_upload, parse_file, parse_filename,
)
# [de-star P1] เดิม `from core_utils import *` — ลบทิ้ง: monolith ไม่ใช้ชื่อใดจาก core_utils
#   เป็น bareword ภายใน และไม่อยู่ใน external getattr-contract (sort_bills_by_date/
#   parse_address_input/clean_pp20_address ถูก import ตรงโดย consumer ที่ต้องใช้)
from webverify import (   # [de-star P1] เดิม `import *` — explicit (online product-verification)
    CONSTRUCTION_DICT, VERIFY_CFG, run_product_verification, web_state_reset,
)
from master import input_master_data, load_master   # [de-star P1] เดิม `import *` — explicit (master-data layer)
# alias ระดับ main → cache "ตัวเดียวกัน" ใน state (reset ใช้ .clear() คง identity)
_FUZZY_DICT_CACHE = state._FUZZY_DICT_CACHE
_PYTHAINLP_CACHE = state._PYTHAINLP_CACHE
# alias ระดับ main → ชี้ "list ตัวเดียวกัน" ใน state (reporting import by-reference จากตรงนี้)
#   reset ใช้ .clear() (ไม่ rebind) → main alias + reporting ref + diagnostics เห็น object เดียวกันเสมอ
_SYSTEM_ISSUES = state._SYSTEM_ISSUES
_SYSTEM_ISSUE_SEEN = state._SYSTEM_ISSUE_SEEN

# ── [de-star P1] public surface ของ monolith = สัญญา getattr ภายนอกที่ผู้ใช้จริงเข้าถึง ──
#   ที่มา (derive จากทั้ง tree, ไม่ใช่เดา): union ของ
#     (ก) ชื่อที่ consumer เข้าถึงผ่าน app.<name> ทั้ง repo
#     (ข) agents/core_access._REQUIRED (22 ชื่อ)
#   การ์ดด้วย test_monolith_surface.py. ก่อนหน้านี้ `import *` บัง surface นี้ไว้แบบ implicit;
#   ตอน de-star เปลี่ยนเป็น explicit `__all__` นี้ทำหน้าที่ (1) เอกสาร public API
#   (2) ให้ linter รู้ว่าชื่อ re-export เหล่านี้ "ถูกใช้" (ดับ F401 เทียม) — golden-neutral
#   (consumer ใช้ getattr ไม่ใช่ `from ... import *` จึงไม่กระทบ runtime).



# ============================================================
# 🆕 v5.4 SPEC CONFIGURATIONS
# ============================================================



# [P-DAG เฟส1] to_conf01 ย้ายไป puopuy_core.py


# [P-DAG พาส3c] web/verify layer (governor _WEB_STATE, web_request, sqlite cache, tier1/tier2 verify, run_product_verification)
#   ย้ายไป webverify.py (online product-verification, leaf) — main re-export ผ่าน `from webverify import *` ด้านบน


# === v9 [ACCURACY]: เพิ่มคำสินค้าจริงที่ขาด → กัน ITM011 ฟ้อง "แผ่นตัด" ว่าใกล้ "แผ่นขัด"
#     (แผ่นตัด=ใบตัด/cutting disc, แผ่นขัด=ใบขัด — คนละสินค้า ไม่ใช่คำสะกดผิด)
import pukpui_modular_consts  # noqa: F401  [SPLIT #3] trigger CONSTRUCTION_DICT enrichment (ย้าย .update ไป consts)


# ============================================================
# 🔒 LOCK CHECK — ตรวจว่าเวอร์ชันยังตรงกับที่ล็อกไว้ (P1: FAIL ดังๆ ไม่ใช่เตือนเงียบ)
#   ใช้ version_gate (source of truth = config._LOCKED) — แทน "พิมพ์ ⚠️ แล้วรันต่อ" เดิม
#   นโยบาย: เพี้ยนระดับอันตราย (major/minor ของ lib หัวใจ, หรือไม่ได้ติดตั้ง) → exit ≠ 0
#           เพี้ยนระดับไม่อันตราย (patch / ชั้นแสดงผล) → เตือน แล้วรันต่อ
#   escape hatch: ตั้ง env PUOPUY_ALLOW_VERSION_MISMATCH=1 เพื่อผ่อนผัน (รับความเสี่ยงเอง)
#   หมายเหตุ: enforce() จะ exit เฉพาะ "เคสที่ควรหยุดจริง" → ปลอดภัยแม้ถูก import โดย harness
# ============================================================
import sys

import version_gate as _version_gate

_version_gate.enforce(strict=False, exit_on_fail=True)

# ============================================================
# 🧹 UTILITIES
# ============================================================
# [P-DAG เฟส2] safe() ย้ายไป puopuy_core.py

# ============================================================
# 🩺 v6.2 OBSERVABILITY — structured system-issue logger
#   เป้าหมาย (TARGET 2): แทน "except: pass / print เฉย ๆ" ในชั้น parse
#   ด้วย record ที่ตามรอยได้ โดย **ไม่แตะ** schema ของ bill/รายงานเดิมเลย
#   - เก็บใน list ระดับโมดูล + พิมพ์รูปแบบมาตรฐาน + เขียน sidecar JSONL
#   - dedupe กัน log ซ้ำ (กัน spam ตามสเปก)
#   - ไม่ทำให้ pipeline ล้ม: ตัว logger เองห่อกันพังไว้
# ============================================================
# [P-DAG พาส2a] _SYSTEM_ISSUES/_SYSTEM_ISSUE_SEEN → state.py ;
#   system_issues_reset/log_system_issue/flush_system_issues_to_disk/_trim_cache → diagnostics.py
#   (main re-export ผ่าน `from diagnostics import *` ด้านบน — อ้าง state._SYSTEM_ISSUES)

# [P-DAG เฟส1] normalize_text/clean_tax_id/... ย้ายไป puopuy_core.py (import ไว้บนสุดแล้ว)
# [P-DAG เฟส2] parse_date_any() ย้ายไป puopuy_dates.py

# ============================================================
# 🆕 [FIX-MERGE] รวมบิลหน้าต่อ — IV ตรง + ลำดับสินค้าต่อเนื่อง
#   เคสจริง: TKH ชีต '3' + '3 (2)' = บิล CB69040116 ใบเดียว (รายการยาวข้ามหน้า)
#   กันพลาด: ชีต '11' + '11(2)' IV คนละเลข = คนละบิล → ไม่รวม
# ============================================================
# [P-DAG พาส3a] parse_filename / merge_continuation_bills / _declared_period_from_filename
#   ย้ายไป parser.py (data-extraction layer) — main re-export ผ่าน `from parser import *` ด้านบน
#   ทำให้ parser พึ่งตัวเองได้ (ลบ _from_main lazy-proxy) + ตัด validators->main cycle


# [P-DAG เฟส2] extract_unit_hint() ย้ายไป puopuy_units.py

# [P-DAG พาส2b] thai_text group → thai_text.py ;
#   _FUZZY_DICT_CACHE/_PYTHAINLP_CACHE → state.py ; PyThaiNLP guard → thai_text.py
#   (main re-export ผ่าน `from thai_text import *` ด้านบน — rules_engine เลิก lazy proxy)



# ============================================================
# [P-DAG พาส2c] ── EXCEL PARSER (read_workbook..parse_file, _dic_*, _pb_*, _tor_*,
#   check_iv_format, taxid/branch scan, amounts, address, audit Text→num) → parser.py
#   (main re-export ผ่าน `from parser import *` ด้านบน)


# [P-DAG พาส3b] clean_pp20_address / parse_address_input ย้ายไป core_utils.py (shared helpers)
#   main re-export ผ่าน `from core_utils import *` ด้านบน


# [P-DAG พาส3d] master-data layer (validate_master_entry/save_master/load_master/
#   parse_master_blob/input_master_data) ย้ายไป master.py — main re-export ผ่าน `from master import *`


# [P-DAG พาส1] match_company → ย้ายไป rules_engine.py


# [P-DAG พาส1] load_product_master + PRODUCT_MASTER → ย้ายไป rules_engine.py

# ============================================================
# 🛡️ RULES ENGINE
# ============================================================
# [P-DAG พาส1] add_issue + 56 กฎ + RULES registry + run_rules → ย้ายไป rules_engine.py
#   (main re-export ผ่าน `from rules_engine import *` ด้านบน — RULES/ฟังก์ชันเป็น object เดียวกัน)


# ============================================================
# 🆕 v6.5 — ตัวอ่าน "งวด (ปี/เดือน) ที่ฝังในเลขที่เอกสาร" รองรับหลายฟอร์แมต
#   ใช้กับ DT004 (วันที่ขัดแย้งกับเลข IV) แทนการเดา IV+YYMM แบบตายตัว
#   *ห้ามทำให้การตรวจเดิม (ไทย YYMM) อ่อนลง* — ฟังก์ชันนี้ครอบของเดิม + ขยายเพิ่ม
#
#   หลักการกัน false positive: อ่านงวดจากเลขได้ "แบบมั่นใจ" เท่านั้นจึงเทียบ
#   อ่านไม่ได้/ไม่เข้าโครงปี-เดือน → คืน None = ไม่ฟันธง (เลข running ล้วน/ฟอร์แมตแปลก)
#
#   ฟอร์แมตที่รองรับ (พบจริงในเอกสารไทย):
#     IV6811xxxx / CB-6904-xxxx / IV-68-110141  → พ.ศ. 2 หลัก + เดือน (+วัน/running)
#     J25110023                                  → ค.ศ. 2 หลัก + เดือน + running
#     256811xxxx                                 → พ.ศ. 4 หลัก + เดือน
#     202511xxxx                                 → ค.ศ. 4 หลัก + เดือน
#     INV-2025-001                               → ค.ศ. 4 หลัก (ปีอย่างเดียว ไม่มีเดือน)
#
#   ช่วงปีที่ยอมรับว่าเป็น "ปีจริง" (กันเลข running บังเอิญหน้าตาเหมือนปี) — สองฐานไม่ทับกัน:
#     พ.ศ. 2 หลัก = 58–82 (พ.ศ.2558–2582 ↔ ค.ศ.2015–2039)
#     ค.ศ. 2 หลัก = 15–39 (ค.ศ.2015–2039)
#     พ.ศ. 4 หลัก = 2558–2582 | ค.ศ. 4 หลัก = 2015–2039
# ============================================================
# [P-DAG เฟส2] _ivp_year2_to_ce() ย้ายไป puopuy_dates.py

# [P-DAG เฟส2] _ivp_year4_to_ce() ย้ายไป puopuy_dates.py

# --- validators layer (validators.py) ---
#   [P-DAG พาส3a] validators นำเข้า dependency จาก leaf modules ตรง ๆ แล้ว
#   จึงไม่ต้องมี import-gate / ลำดับนิยามใน main อีก (ตัด validators -> main cycle)
from validators import (   # [de-star P1] เดิม `import *` — explicit; re-export check_*/apply_*_crosscheck ให้ agents
    CFG, apply_iv_period_crosscheck, apply_sheet_date_crosscheck, apply_missing_date_check,
    check_duplicate_items, check_filename_consistency,
    check_invoice_sequence, check_iv_date_sequence, check_product_typos,
    log_system_issue, detect_iv_period_mismatch,
)



# [P-DAG พาส3f] check_filename_consistency ย้ายไป validators.py — re-export ผ่าน `from validators import *`


# ============================================================
# 🔬 PRODUCT VERIFICATION (Tier 1 + Tier 2)
# ============================================================



# ============================================================
# 📤 UPLOAD
# ============================================================
# [P-DAG พาส3g] get_files_via_upload/drive ย้ายไป parser.py (ชั้นค้นไฟล์) — re-export ผ่าน `from parser import *`


# [P-DAG พาส3b] sort_bills_by_date ย้ายไป core_utils.py (ใช้ร่วม analytics/reporting)

# --- analytics layer (analytics.py) ---
#   [P-DAG พาส3b] analytics นำเข้า dependency จาก leaf modules ตรง ๆ แล้ว (ตัด analytics -> main cycle)
from analytics import (   # [de-star P1] เดิม `import *` — explicit; re-export compute_bill_confidence/summarize_by_company/build_unit_index/addon_check_withholding ให้ agents
    addon_check_withholding, build_unit_index, cluster_products,
    compute_bill_confidence, detect_price_outliers, detect_unit_anomalies,
    load_audit_excel, summarize_by_company,
)


# ============================================================
# 🆕 v5.8r — เลขที่เอกสาร "ตามหน้าเอกสารจริง" (เก็บขีด/เว้นวรรค)
#   ใช้แสดงในรายงานเท่านั้น — การตรวจสอบยังใช้ iv_number แบบลบขีดเหมือนเดิม
# ============================================================
# [P-DAG พาส2c] _raw_iv_form → parser.py


# ============================================================
# 📊 v5.5 ANALYTICS MODULE — Pattern Clustering + Plotly Dashboard
# ============================================================

# [P-DAG พาส3e] analytics ตัวคำนวณบริสุทธิ์ (load_audit_excel/cluster_*/detect_*) ย้ายไป analytics.py — re-export ผ่าน `from analytics import *`


# [P-DAG พาส3f] check_duplicate_items ย้ายไป validators.py — re-export ผ่าน `from validators import *`


# [P-DAG พาส3b] thin / bottom_only (openpyxl styles) ย้ายไป config.py — main+reporting รับผ่าน `from config import *`

# --- reporting layer (reporting.py) ---
#   [P-DAG พาส3b] reporting นำเข้า dependency จาก leaf (thai_text/rules_engine/state/core_utils)
#   + style จาก config แล้ว → ตัด reporting -> main cycle, ไม่ต้องมี import-gate ที่นี่
from reporting import (   # [de-star P1] เดิม `import *` — explicit; re-export RULES/build_clean_report/export_excel ให้ agents/main
    ANALYTICS_CFG, APP_VERSION, PYTHAINLP_AVAILABLE, RULES,
    build_clean_report, build_dashboard_figs,
    display_executive_dashboard, display_low_confidence_bills,
    export_excel, export_verification_to_excel, render_dashboard_html,
)


# ============================================================
# 🚦 main() PHASES (extracted, slice 3A) — behavior 100% เดิม
#   ย้ายบล็อกใน main ออกมาเป็นฟังก์ชันชื่อชัด: logic/ลำดับ/print เดิมทุกอย่าง
# ============================================================


# ===========================================================================
# ⭐ SINGLE SOURCE OF TRUTH — "ลำดับศักดิ์สิทธิ์" ของการตรวจหลัก (audit core)
# ---------------------------------------------------------------------------
# เดิมลำดับนี้ถูก "คัดลอกด้วยมือ" ไว้ 3 ที่ (main() / agents.orchestrator._run_audit_core /
# golden_master.py) → แก้ที่หนึ่งลืมอีกที่ = engine กับ agent เพี้ยนเงียบ ๆ, golden hash ดริฟต์
# โดยไม่มีใครรู้จนกว่าจะรัน regression. รวมเป็นฟังก์ชันเดียวตรงนี้ → ทุกเส้นเรียกตัวเดียวกัน
# → "engine == agent == golden" รับประกันด้วยโครงสร้าง ไม่ใช่ด้วยวินัยการก๊อป.
#
# แบ่ง 2 เฟสให้ตรงกับโครงสร้าง main() เป๊ะ (main แทรก "การแสดงผล" ไว้ระหว่างสองเฟส):
#   เฟส 1 = _audit_core_rules()      : dup → rules → iv/typos/summary  (ก่อนแดชบอร์ด)
#   เฟส 2 = _audit_core_crosschecks(): apply_iv_period + apply_sheet_date  (หลังแดชบอร์ด)
# เส้นที่ไม่มีการแสดงผลคั่น (orchestrator / golden_master) ใช้ run_audit_core() = เฟส1+เฟส2.
#
# byte-identical: บนชุดข้อมูล golden ทั้ง 3 ขั้นในเฟส1 "ไม่เคยโยน exception" → ใส่ try/except
# (error isolation) ไม่เปลี่ยนผลลัพธ์/ลำดับ → golden hash คงเดิม. ข้อความ console วิ่งผ่าน
# callback `log` → main คงพิมพ์เหมือนเดิมทุกบรรทัด, ส่วน orchestrator/golden_master เงียบเหมือนเดิม.
# ===========================================================================


# ============================================================
# 🎁 v5.8q ADD-ON PACK — 7 Features for Accountants (Additive)
# ============================================================
# วิธีใช้: paste บล็อกนี้ "ต่อท้าย" โค้ดหลัก v5.8 ทั้งหมด
#         แล้วเรียก run_addon_pack(all_bills, out_excel_path) หลัง export_excel
#
# ฟีเจอร์:
#   1. DUP001 - Duplicate Bill Detection (บิลซ้ำ)
#   2. WHT001 - Withholding Tax 3% Check (ภงด.53)
#   3. RND001 - Round Number Anomaly (ยอดปัดสวยผิดปกติ)
#   4. PER001 - Period Coverage Analysis (ความครบของงวด)
#   5. VND001 - Vendor Risk Profile (โปรไฟล์ความเสี่ยงคู่ค้า)
#   6. BNF001 - Benford's Law Digit Distribution (ตรวจหลอกแบบสถิติ)
#   7. Audit Trail Sheet (บันทึกการตรวจ + auto-fix)
#
# ไม่กระทบ:
#   - ไม่แก้ RULES dict
#   - ไม่แก้ฟังก์ชัน parse / rules / cross-bill เดิม
#   - เป็นการ "อ่าน" บิลที่ parse แล้วเพื่อสร้างชีตเพิ่มใน Excel
# ============================================================


# ============================================================
# 📍 วิธีเรียกใช้ — เพิ่ม 1 บรรทัดใน main() หลัง export_excel
# ============================================================
#
# ในฟังก์ชัน main() หา:
#     if export_excel(all_bills, summary, iv_issues, typos, filename_issues, out):
#
# หลังบล็อกนั้น (อาจหลัง verification หรือก่อน analytics) เพิ่ม:
#     run_addon_pack(all_bills, out)
#
# หรือถ้าอยากเรียก standalone (รัน addon ทีหลัง):
#     run_addon_pack(all_bills, 'audit_v58_xxxxx.xlsx')
# ============================================================


# ============================================================
# v8.2 FIX: เติม entry point กลับ — ตอนต่อโค้ด addon ท้ายไฟล์ บล็อกนี้หายไป
#   ทำให้รัน `python ไฟล์.py` แล้วโปรแกรม "ไม่ทำงาน" (นิยามฟังก์ชันครบแล้วจบ)
#   (import ไฟล์นี้จะไม่สั่งรัน main เพื่อให้ reuse/unit test ได้)
# ============================================================


# [SPLIT #3] re-export surface — ชื่อที่ funcs/top ดึงไปใช้ (explicit; ดับ F401 ของ re-export)
__all__ = [
    'ANALYTICS_CFG', 'APP_VERSION', 'CFG', 'CONSTRUCTION_DICT',
    'Counter', 'HTML', 'LEAN_REPORT', 'PYTHAINLP_AVAILABLE',
    'RULES', 'SEVERITY_ICON', 'THAI_TYPO_PATTERNS', 'VERIFY_CFG',
    '_CAPTURED_HTML', '_D', '_FUZZY_DICT_CACHE', '_IN_NOTEBOOK',
    '_PYTHAINLP_CACHE', '_SYSTEM_ISSUES', '_taxid_checksum_ok', '_trim_cache',
    '_vat_tolerance', 'addon_check_withholding', 'apply_iv_period_crosscheck', 'apply_missing_date_check', 'apply_sheet_date_crosscheck',
    'audit_text_num_reset', 'audit_text_num_summary', 'audit_today', 'build_clean_report',
    'build_dashboard_figs', 'build_unit_index', 'check_duplicate_items', 'check_filename_consistency',
    'check_invoice_sequence', 'check_iv_date_sequence', 'check_product_typos', 'clean_tax_id',
    'cluster_products', 'compute_bill_confidence', 'datetime', 'detect_iv_period_mismatch',
    'detect_price_outliers', 'detect_unit_anomalies', 'display', 'display_executive_dashboard',
    'display_low_confidence_bills', 'export_excel', 'export_verification_to_excel', 'file_guard',
    'flush_system_issues_to_disk', 'gc', 'get_files_via_drive', 'get_files_via_upload',
    'input_master_data', 'load_audit_excel', 'load_master', 'log_system_issue',
    'match_company', 'os', 'parse_file', 'parse_filename',
    'render_dashboard_html', 'run_product_verification', 'run_rules', 'state',
    'summarize_by_company', 'sys', 'system_issues_reset', 'tqdm',
    'traceback', 'web_state_reset',
]
